alter session set container=XEPDB1;
create table onyx_account (
  account_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  account_code varchar2(30) not null,
  account_name_ar varchar2(200) not null,
  account_name_en varchar2(200),
  account_type varchar2(30) default 'GENERAL' not null,
  parent_code varchar2(30),
  parent_id number references onyx_account(account_id),
  active_flag number(1) default 1 not null,
  opening_balance number(18,3) default 0 not null,
  created_at timestamp default systimestamp not null,
  constraint uq_onyx_account_code unique(company_id, account_code),
  constraint ck_onyx_account_active check(active_flag in (0,1))
);
create table onyx_journal_entry (
  entry_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number not null references onyx_fiscal_year(fiscal_year_id),
  entry_no varchar2(40) not null,
  entry_date date not null,
  description_ar varchar2(500) not null,
  status_code varchar2(15) default 'DRAFT' not null,
  created_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  constraint uq_onyx_entry_no unique(company_id, entry_no),
  constraint ck_onyx_entry_status check(status_code in ('DRAFT','POSTED','VOID'))
);
create table onyx_journal_line (
  line_id number generated by default as identity primary key,
  entry_id number not null references onyx_journal_entry(entry_id) on delete cascade,
  account_id number not null references onyx_account(account_id),
  line_description_ar varchar2(500),
  debit number(18,3) default 0 not null,
  credit number(18,3) default 0 not null,
  constraint ck_onyx_line_amount check((debit > 0 and credit = 0) or (credit > 0 and debit = 0) or (debit = 0 and credit = 0))
);
create index ix_onyx_account_company on onyx_account(company_id, account_code);
create index ix_onyx_entry_date on onyx_journal_entry(company_id, entry_date);
create index ix_onyx_line_entry on onyx_journal_line(entry_id);
commit;
exit;
