alter session set container=XEPDB1;
create table onyx_contact (
  contact_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  contact_type varchar2(12) not null,
  code varchar2(30) not null,
  name_ar varchar2(200) not null,
  phone varchar2(40),
  email varchar2(160),
  tax_number varchar2(40),
  credit_limit number(18,3) default 0 not null,
  active_flag number(1) default 1 not null,
  created_at timestamp default systimestamp not null,
  constraint uq_onyx_contact unique(company_id, contact_type, code),
  constraint ck_onyx_contact_type check(contact_type in ('CUSTOMER','VENDOR'))
);
create table onyx_item (
  item_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  item_code varchar2(40) not null,
  item_name_ar varchar2(200) not null,
  unit_name varchar2(40) default 'قطعة' not null,
  cost_price number(18,3) default 0 not null,
  sale_price number(18,3) default 0 not null,
  quantity number(18,3) default 0 not null,
  reorder_level number(18,3) default 0 not null,
  active_flag number(1) default 1 not null,
  created_at timestamp default systimestamp not null,
  constraint uq_onyx_item unique(company_id, item_code)
);
create table onyx_invoice (
  invoice_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  invoice_type varchar2(12) not null,
  invoice_no varchar2(40) not null,
  contact_id number references onyx_contact(contact_id),
  invoice_date date default trunc(sysdate) not null,
  subtotal number(18,3) default 0 not null,
  tax_amount number(18,3) default 0 not null,
  total_amount number(18,3) default 0 not null,
  status_code varchar2(15) default 'DRAFT' not null,
  created_at timestamp default systimestamp not null,
  constraint uq_onyx_invoice unique(company_id, invoice_type, invoice_no),
  constraint ck_onyx_invoice_type check(invoice_type in ('SALE','PURCHASE')),
  constraint ck_onyx_invoice_status check(status_code in ('DRAFT','POSTED','VOID'))
);
create table onyx_invoice_line (
  line_id number generated by default as identity primary key,
  invoice_id number not null references onyx_invoice(invoice_id) on delete cascade,
  item_id number not null references onyx_item(item_id),
  quantity number(18,3) not null,
  unit_price number(18,3) not null,
  discount_amount number(18,3) default 0 not null,
  line_total number(18,3) not null
);
create index ix_onyx_contact_company on onyx_contact(company_id, contact_type, code);
create index ix_onyx_item_company on onyx_item(company_id, item_code);
create index ix_onyx_invoice_date on onyx_invoice(company_id, invoice_date);
commit;
exit;
