-- Mido accounting core: currencies, posted journals, fiscal close and audit metadata
-- Run once after migrations 001-007.
alter session set container=XEPDB1;

create table onyx_currency (
  currency_code varchar2(3) primary key,
  currency_name_ar varchar2(100) not null,
  symbol varchar2(10),
  active_flag number(1) default 1 not null,
  constraint ck_onyx_currency_active check(active_flag in (0,1))
);

create table onyx_exchange_rate (
  rate_id number generated by default as identity primary key,
  currency_code varchar2(3) not null references onyx_currency(currency_code),
  rate_date date not null,
  rate_to_base number(24,10) not null,
  source_code varchar2(40),
  approved_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  constraint ck_onyx_rate_positive check(rate_to_base > 0),
  constraint uq_onyx_rate unique(currency_code, rate_date)
);

insert into onyx_currency(currency_code,currency_name_ar,symbol) values ('SAR','ريال سعودي','ر.س');
insert into onyx_currency(currency_code,currency_name_ar,symbol) values ('YER','ريال يمني','ر.ي');
insert into onyx_currency(currency_code,currency_name_ar,symbol) values ('USD','دولار أمريكي','$');
insert into onyx_currency(currency_code,currency_name_ar,symbol) values ('EUR','يورو','€');

alter table onyx_journal_entry add (
  source_code varchar2(30) default 'MANUAL' not null,
  currency_code varchar2(3) default 'SAR' not null references onyx_currency(currency_code),
  exchange_rate number(24,10) default 1 not null,
  posted_at timestamp,
  posted_by number references onyx_user(user_id),
  reversal_entry_id number references onyx_journal_entry(entry_id)
);

alter table onyx_journal_line add (
  foreign_amount number(24,10),
  line_currency_code varchar2(3) references onyx_currency(currency_code),
  line_exchange_rate number(24,10)
);

alter table onyx_invoice add (
  currency_code varchar2(3) default 'SAR' not null references onyx_currency(currency_code),
  exchange_rate number(24,10) default 1 not null,
  base_subtotal number(24,3) default 0 not null,
  base_total_amount number(24,3) default 0 not null
);

create table onyx_fiscal_close (
  close_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  fiscal_year_id number not null references onyx_fiscal_year(fiscal_year_id),
  opening_year_id number references onyx_fiscal_year(fiscal_year_id),
  close_date date not null,
  net_income number(24,3) not null,
  closing_entry_id number references onyx_journal_entry(entry_id),
  opening_entry_id number references onyx_journal_entry(entry_id),
  status_code varchar2(15) default 'DRAFT' not null,
  created_by number references onyx_user(user_id),
  approved_by number references onyx_user(user_id),
  approved_at timestamp,
  constraint ck_onyx_close_status check(status_code in ('DRAFT','APPROVED','REVERSED')),
  constraint uq_onyx_close_year unique(company_id, fiscal_year_id)
);

create table onyx_audit_event (
  audit_id number generated by default as identity primary key,
  company_id number references onyx_company(company_id),
  user_id number references onyx_user(user_id),
  entity_type varchar2(40) not null,
  entity_id number,
  action_code varchar2(30) not null,
  before_json clob,
  after_json clob,
  created_at timestamp default systimestamp not null
);

create index ix_onyx_rate_date on onyx_exchange_rate(currency_code, rate_date);
create index ix_onyx_entry_source on onyx_journal_entry(company_id, source_code, entry_date);
create index ix_onyx_audit_entity on onyx_audit_event(entity_type, entity_id, created_at);

create or replace trigger trg_onyx_posted_journal_guard
before update of status_code on onyx_journal_entry
for each row
when (new.status_code = 'POSTED')
declare
  v_debit number;
  v_credit number;
begin
  select nvl(sum(debit),0), nvl(sum(credit),0)
    into v_debit, v_credit
    from onyx_journal_line
   where entry_id = :new.entry_id;
  if abs(v_debit - v_credit) > 0.0005 or v_debit = 0 then
    raise_application_error(-20031, 'لا يمكن ترحيل قيد غير متوازن أو فارغ.');
  end if;
  :new.posted_at := systimestamp;
end;
/

create or replace view onyx_trial_balance_v as
select e.company_id, e.fiscal_year_id, l.account_id,
       sum(l.debit) total_debit, sum(l.credit) total_credit,
       sum(l.debit - l.credit) balance
  from onyx_journal_entry e join onyx_journal_line l on l.entry_id=e.entry_id
 where e.status_code='POSTED'
 group by e.company_id, e.fiscal_year_id, l.account_id;

commit;
exit;
