-- Mido invoice posting: invoice -> journal -> stock movement in one transaction
alter session set container=XEPDB1;

alter table onyx_invoice add (
  journal_entry_id number references onyx_journal_entry(entry_id),
  posted_at timestamp,
  posted_by number references onyx_user(user_id)
);

alter table onyx_invoice_line add (
  unit_cost number(18,3) default 0 not null,
  base_line_total number(24,3) default 0 not null
);

create table onyx_warehouse (
  warehouse_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  warehouse_code varchar2(30) not null,
  warehouse_name_ar varchar2(200) not null,
  active_flag number(1) default 1 not null,
  constraint uq_onyx_warehouse unique(company_id, warehouse_code)
);

create table onyx_stock_movement (
  movement_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  warehouse_id number not null references onyx_warehouse(warehouse_id),
  item_id number not null references onyx_item(item_id),
  invoice_id number references onyx_invoice(invoice_id),
  movement_type varchar2(20) not null,
  quantity number(24,3) not null,
  unit_cost number(24,3) default 0 not null,
  movement_date date default trunc(sysdate) not null,
  created_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  constraint ck_onyx_stock_type check(movement_type in ('PURCHASE','SALE','RETURN_IN','RETURN_OUT','ADJUSTMENT','TRANSFER_IN','TRANSFER_OUT')),
  constraint ck_onyx_stock_qty check(quantity <> 0)
);

create table onyx_item_balance (
  warehouse_id number not null references onyx_warehouse(warehouse_id),
  item_id number not null references onyx_item(item_id),
  quantity number(24,3) default 0 not null,
  average_cost number(24,3) default 0 not null,
  updated_at timestamp default systimestamp not null,
  constraint pk_onyx_item_balance primary key(warehouse_id, item_id),
  constraint ck_onyx_item_balance_qty check(quantity >= 0)
);

create index ix_onyx_stock_invoice on onyx_stock_movement(invoice_id);
create index ix_onyx_stock_item_date on onyx_stock_movement(item_id, movement_date);
create index ix_onyx_invoice_journal on onyx_invoice(journal_entry_id);

create or replace view onyx_stock_balance_v as
select warehouse_id, item_id, sum(quantity) quantity,
       sum(quantity * unit_cost) / nullif(sum(quantity),0) average_cost
  from onyx_stock_movement
 group by warehouse_id, item_id;

create or replace trigger trg_onyx_invoice_posted_guard
before update of status_code on onyx_invoice
for each row
when (new.status_code = 'POSTED')
begin
  if :new.journal_entry_id is null then
    raise_application_error(-20041, 'لا يمكن ترحيل الفاتورة قبل ربطها بقيد محاسبي.');
  end if;
  :new.posted_at := systimestamp;
end;
/

commit;
exit;
