-- Mido original document cycle: orders, receipts, deliveries and returns
alter session set container=XEPDB1;

create table onyx_trade_document (
  document_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number references onyx_fiscal_year(fiscal_year_id),
  warehouse_id number references onyx_warehouse(warehouse_id),
  contact_id number references onyx_contact(contact_id),
  source_document_id number references onyx_trade_document(document_id),
  document_type varchar2(24) not null,
  document_no varchar2(40) not null,
  document_date date default trunc(sysdate) not null,
  currency_code varchar2(12) default 'SAR' not null,
  exchange_rate number(18,6) default 1 not null,
  subtotal number(24,3) default 0 not null,
  tax_amount number(24,3) default 0 not null,
  total_amount number(24,3) default 0 not null,
  status_code varchar2(24) default 'DRAFT' not null,
  created_by number references onyx_user(user_id),
  approved_by number references onyx_user(user_id),
  posted_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  approved_at timestamp,
  posted_at timestamp,
  constraint uq_onyx_trade_doc unique(company_id, document_type, document_no),
  constraint ck_onyx_trade_type check(document_type in ('SALES_ORDER','PURCHASE_ORDER','DELIVERY_NOTE','RECEIPT_NOTE','SALES_INVOICE','PURCHASE_INVOICE','SALES_RETURN','PURCHASE_RETURN')),
  constraint ck_onyx_trade_status check(status_code in ('DRAFT','APPROVED','PARTIALLY_FULFILLED','FULFILLED','POSTED','VOID','RETURNED')),
  constraint ck_onyx_trade_rate check(exchange_rate > 0),
  constraint ck_onyx_trade_amounts check(subtotal >= 0 and tax_amount >= 0 and total_amount >= 0)
);

create table onyx_trade_document_line (
  line_id number generated by default as identity primary key,
  document_id number not null references onyx_trade_document(document_id) on delete cascade,
  item_id number not null references onyx_item(item_id),
  source_line_id number references onyx_trade_document_line(line_id),
  quantity number(24,3) not null,
  fulfilled_quantity number(24,3) default 0 not null,
  unit_price number(24,3) default 0 not null,
  unit_cost number(24,3) default 0 not null,
  discount_amount number(24,3) default 0 not null,
  tax_amount number(24,3) default 0 not null,
  line_total number(24,3) not null,
  constraint ck_onyx_trade_line_qty check(quantity > 0 and fulfilled_quantity >= 0 and fulfilled_quantity <= quantity),
  constraint ck_onyx_trade_line_price check(unit_price >= 0 and unit_cost >= 0 and discount_amount >= 0 and tax_amount >= 0 and line_total >= 0)
);

create table onyx_document_link (
  link_id number generated by default as identity primary key,
  parent_document_id number not null references onyx_trade_document(document_id),
  child_document_id number not null references onyx_trade_document(document_id),
  linked_at timestamp default systimestamp not null,
  linked_by number references onyx_user(user_id),
  constraint uq_onyx_doc_link unique(parent_document_id, child_document_id),
  constraint ck_onyx_doc_link_self check(parent_document_id <> child_document_id)
);

create index ix_onyx_trade_doc_scope on onyx_trade_document(company_id, branch_id, document_type, document_date);
create index ix_onyx_trade_doc_status on onyx_trade_document(status_code, contact_id);
create index ix_onyx_trade_doc_source on onyx_trade_document(source_document_id);
create index ix_onyx_trade_line_doc on onyx_trade_document_line(document_id);
create index ix_onyx_trade_line_item on onyx_trade_document_line(item_id);
create index ix_onyx_doc_link_parent on onyx_document_link(parent_document_id);
create index ix_onyx_doc_link_child on onyx_document_link(child_document_id);

create or replace trigger trg_onyx_trade_posted_guard
before update of status_code on onyx_trade_document
for each row
when (new.status_code = 'POSTED')
begin
  if :new.posted_by is null then
    raise_application_error(-20051, 'لا يمكن ترحيل المستند قبل تحديد المستخدم المرحّل.');
  end if;
  :new.posted_at := systimestamp;
end;
/

create or replace view onyx_trade_document_flow_v as
select d.document_id,d.company_id,d.branch_id,d.contact_id,d.document_type,d.document_no,d.document_date,
       d.source_document_id,d.status_code,d.subtotal,d.tax_amount,d.total_amount,
       count(l.line_id) line_count,
       nvl(sum(l.quantity),0) total_quantity,
       nvl(sum(l.fulfilled_quantity),0) fulfilled_quantity
  from onyx_trade_document d
  left join onyx_trade_document_line l on l.document_id=d.document_id
 group by d.document_id,d.company_id,d.branch_id,d.contact_id,d.document_type,d.document_no,d.document_date,
          d.source_document_id,d.status_code,d.subtotal,d.tax_amount,d.total_amount;

commit;
exit;
