-- Commercial modules: cash/bank vouchers, expenses/income, fixed assets and depreciation
alter session set container=XEPDB1;

create table onyx_cash_voucher (
  voucher_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number references onyx_fiscal_year(fiscal_year_id),
  voucher_type varchar2(12) not null,
  voucher_no varchar2(40) not null,
  voucher_date date default trunc(sysdate) not null,
  cash_account_id number not null references onyx_account(account_id),
  journal_entry_id number references onyx_journal_entry(entry_id),
  total_amount number(24,3) not null,
  status_code varchar2(15) default 'DRAFT' not null,
  description_ar varchar2(500),
  created_by number references onyx_user(user_id),
  constraint ck_onyx_voucher_type check(voucher_type in ('RECEIPT','PAYMENT','TRANSFER')),
  constraint ck_onyx_voucher_amount check(total_amount > 0),
  constraint uq_onyx_voucher_no unique(company_id, voucher_type, voucher_no)
);

create table onyx_cash_voucher_line (
  line_id number generated by default as identity primary key,
  voucher_id number not null references onyx_cash_voucher(voucher_id) on delete cascade,
  account_id number not null references onyx_account(account_id),
  amount number(24,3) not null,
  line_description_ar varchar2(500),
  constraint ck_onyx_voucher_line_amount check(amount > 0)
);

create table onyx_expense_income (
  operation_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number references onyx_fiscal_year(fiscal_year_id),
  operation_type varchar2(10) not null,
  operation_no varchar2(40) not null,
  operation_date date default trunc(sysdate) not null,
  description_ar varchar2(500) not null,
  amount number(24,3) not null,
  cash_account_id number not null references onyx_account(account_id),
  category_account_id number not null references onyx_account(account_id),
  journal_entry_id number references onyx_journal_entry(entry_id),
  status_code varchar2(15) default 'DRAFT' not null,
  created_by number references onyx_user(user_id),
  constraint ck_onyx_income_expense_type check(operation_type in ('EXPENSE','INCOME')),
  constraint ck_onyx_income_expense_amount check(amount > 0),
  constraint uq_onyx_income_expense_no unique(company_id, operation_type, operation_no)
);

create table onyx_fixed_asset (
  asset_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  asset_code varchar2(40) not null,
  asset_name_ar varchar2(200) not null,
  acquisition_date date not null,
  cost_amount number(24,3) not null,
  salvage_amount number(24,3) default 0 not null,
  useful_life_months number not null,
  accumulated_depreciation number(24,3) default 0 not null,
  asset_account_id number not null references onyx_account(account_id),
  depreciation_expense_account_id number not null references onyx_account(account_id),
  accumulated_account_id number not null references onyx_account(account_id),
  status_code varchar2(15) default 'ACTIVE' not null,
  constraint uq_onyx_asset_code unique(company_id, asset_code),
  constraint ck_onyx_asset_values check(cost_amount > 0 and salvage_amount >= 0 and salvage_amount <= cost_amount and useful_life_months > 0),
  constraint ck_onyx_asset_status check(status_code in ('ACTIVE','DISPOSED','FULLY_DEPRECIATED'))
);

create table onyx_asset_depreciation (
  depreciation_id number generated by default as identity primary key,
  asset_id number not null references onyx_fixed_asset(asset_id),
  fiscal_year_id number references onyx_fiscal_year(fiscal_year_id),
  period_date date not null,
  months_count number not null,
  depreciation_amount number(24,3) not null,
  journal_entry_id number references onyx_journal_entry(entry_id),
  created_by number references onyx_user(user_id),
  constraint ck_onyx_depreciation_values check(months_count > 0 and depreciation_amount > 0)
);

create index ix_onyx_voucher_scope on onyx_cash_voucher(company_id, branch_id, fiscal_year_id, voucher_date);
create index ix_onyx_income_expense_scope on onyx_expense_income(company_id, branch_id, fiscal_year_id, operation_date);
create index ix_onyx_asset_scope on onyx_fixed_asset(company_id, branch_id, status_code);
create index ix_onyx_asset_dep on onyx_asset_depreciation(asset_id, period_date);
commit;
exit;
