-- Incremental CRUD additions for databases that already ran migration 013
alter session set container=XEPDB1;

alter table onyx_cash_voucher add (journal_entry_id number references onyx_journal_entry(entry_id));

create table onyx_expense_income (
  operation_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number references onyx_fiscal_year(fiscal_year_id),
  operation_type varchar2(10) not null,
  operation_no varchar2(40) not null,
  operation_date date default trunc(sysdate) not null,
  description_ar varchar2(500) not null,
  amount number(24,3) not null,
  cash_account_id number not null references onyx_account(account_id),
  category_account_id number not null references onyx_account(account_id),
  journal_entry_id number references onyx_journal_entry(entry_id),
  status_code varchar2(15) default 'DRAFT' not null,
  created_by number references onyx_user(user_id),
  constraint ck_onyx_income_expense_type check(operation_type in ('EXPENSE','INCOME')),
  constraint ck_onyx_income_expense_amount check(amount > 0),
  constraint uq_onyx_income_expense_no unique(company_id, operation_type, operation_no)
);

create index ix_onyx_income_expense_scope on onyx_expense_income(company_id, branch_id, fiscal_year_id, operation_date);
commit;
exit;
