-- Accounts receivable/payable payments, allocations and credit control
alter session set container=XEPDB1;

alter table onyx_contact add (
  credit_limit number(24,3) default 0 not null,
  payment_terms_days number default 0 not null
);

create table onyx_ar_payment (
  payment_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number references onyx_fiscal_year(fiscal_year_id),
  contact_id number not null references onyx_contact(contact_id),
  payment_type varchar2(10) not null,
  payment_no varchar2(40) not null,
  payment_date date default trunc(sysdate) not null,
  cash_account_id number not null references onyx_account(account_id),
  amount number(24,3) not null,
  allocated_amount number(24,3) default 0 not null,
  unapplied_amount number(24,3) default 0 not null,
  description_ar varchar2(500),
  cash_voucher_id number references onyx_cash_voucher(voucher_id),
  status_code varchar2(15) default 'DRAFT' not null,
  created_by number references onyx_user(user_id),
  created_at timestamp default systimestamp not null,
  constraint ck_onyx_ar_payment_type check(payment_type in ('RECEIPT','PAYMENT')),
  constraint ck_onyx_ar_payment_amount check(amount > 0 and allocated_amount >= 0 and unapplied_amount >= 0 and allocated_amount + unapplied_amount = amount),
  constraint ck_onyx_ar_payment_status check(status_code in ('DRAFT','POSTED','VOID')),
  constraint uq_onyx_ar_payment_no unique(company_id, payment_type, payment_no)
);

create table onyx_ar_allocation (
  allocation_id number generated by default as identity primary key,
  payment_id number not null references onyx_ar_payment(payment_id) on delete cascade,
  invoice_id number not null references onyx_invoice(invoice_id),
  amount number(24,3) not null,
  created_at timestamp default systimestamp not null,
  constraint ck_onyx_ar_allocation_amount check(amount > 0),
  constraint uq_onyx_ar_payment_invoice unique(payment_id, invoice_id)
);

create index ix_onyx_ar_payment_contact on onyx_ar_payment(company_id, branch_id, contact_id, payment_date);
create index ix_onyx_ar_allocation_invoice on onyx_ar_allocation(invoice_id);
create index ix_onyx_invoice_due_date on onyx_invoice(company_id, branch_id, due_date, status_code);
commit;
exit;
