-- Invoice workflow 3.1: draft -> approved -> posted -> void
alter table onyx_invoice drop constraint ck_onyx_invoice_status;
alter table onyx_invoice add constraint ck_onyx_invoice_status check(status_code in ('DRAFT','APPROVED','POSTED','VOID'));

create table onyx_invoice_event (
  event_id number generated by default as identity primary key,
  invoice_id number not null references onyx_invoice(invoice_id),
  action_code varchar2(20) not null,
  from_status varchar2(15),
  to_status varchar2(15) not null,
  user_id number references onyx_user(user_id),
  event_at timestamp default systimestamp not null,
  constraint ck_onyx_invoice_event_action check(action_code in ('CREATE','APPROVE','POST','VOID'))
);

create index ix_onyx_invoice_event_invoice on onyx_invoice_event(invoice_id, event_at);
commit;
exit;
