-- Fiscal periods, close checks, close runs and reopen audit trail
alter session set container=XEPDB1;

create table onyx_fiscal_period (
  period_id number generated by default as identity primary key,
  company_id number not null references onyx_company(company_id),
  branch_id number not null references onyx_branch(branch_id),
  fiscal_year_id number not null references onyx_fiscal_year(fiscal_year_id),
  period_code varchar2(20) not null,
  period_name_ar varchar2(100) not null,
  start_date date not null,
  end_date date not null,
  status_code varchar2(15) default 'OPEN' not null,
  closed_by number references onyx_user(user_id),
  closed_at timestamp,
  reopened_by number references onyx_user(user_id),
  reopened_at timestamp,
  constraint ck_onyx_period_dates check(end_date >= start_date),
  constraint ck_onyx_period_status check(status_code in ('OPEN','SOFT_CLOSED','CLOSED','REOPENED')),
  constraint uq_onyx_period_code unique(company_id, branch_id, fiscal_year_id, period_code),
  constraint uq_onyx_period_dates unique(company_id, branch_id, fiscal_year_id, start_date, end_date)
);

create table onyx_period_close_run (
  close_run_id number generated by default as identity primary key,
  period_id number not null references onyx_fiscal_period(period_id),
  status_code varchar2(15) default 'STARTED' not null,
  started_by number references onyx_user(user_id),
  started_at timestamp default systimestamp not null,
  completed_at timestamp,
  checks_passed number default 0 not null,
  checks_failed number default 0 not null,
  notes_ar varchar2(1000),
  constraint ck_onyx_close_run_status check(status_code in ('STARTED','PASSED','FAILED','EXECUTED'))
);

create table onyx_period_close_check (
  check_id number generated by default as identity primary key,
  close_run_id number not null references onyx_period_close_run(close_run_id) on delete cascade,
  check_code varchar2(50) not null,
  check_name_ar varchar2(200) not null,
  status_code varchar2(12) not null,
  expected_value number,
  actual_value number,
  error_message_ar varchar2(1000),
  checked_at timestamp default systimestamp not null,
  constraint ck_onyx_close_check_status check(status_code in ('PASS','WARNING','FAIL')),
  constraint uq_onyx_close_check unique(close_run_id, check_code)
);

create table onyx_period_reopen_log (
  reopen_id number generated by default as identity primary key,
  period_id number not null references onyx_fiscal_period(period_id),
  reopened_by number not null references onyx_user(user_id),
  reopened_at timestamp default systimestamp not null,
  reason_ar varchar2(1000) not null,
  approved_by number references onyx_user(user_id)
);

merge into onyx_permission p using (select 'CLOSE_PERIOD' permission_code, 'إغلاق الفترة المالية' permission_name_ar from dual) s on (p.permission_code=s.permission_code)
when not matched then insert(permission_code,permission_name_ar) values(s.permission_code,s.permission_name_ar);
merge into onyx_permission p using (select 'REOPEN_PERIOD' permission_code, 'إعادة فتح الفترة المالية' permission_name_ar from dual) s on (p.permission_code=s.permission_code)
when not matched then insert(permission_code,permission_name_ar) values(s.permission_code,s.permission_name_ar);

create index ix_onyx_period_scope on onyx_fiscal_period(company_id, branch_id, fiscal_year_id, start_date, end_date);
create index ix_onyx_close_run_period on onyx_period_close_run(period_id, started_at);
create index ix_onyx_reopen_period on onyx_period_reopen_log(period_id, reopened_at);
commit;
exit;
