-- GENERATED ORACLE FORMS TRIGGERS — EXP_REPORT_TO_EXCEEL.fmx
-- These are Forms Builder trigger bodies, not SQL*Plus statements.
-- Status: SCAFFOLD_ONLY; map exact blocks/items from FMB/source before use.
-- Package wrapper: RB_EXP_REPORT_TO_EXCEEL_5D757

-- PRE-FORM
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.initialize('EXP_REPORT_TO_EXCEEL');
EXCEPTION
  WHEN OTHERS THEN
    MESSAGE('Initialization failed: ' || SQLERRM);
    RAISE FORM_TRIGGER_FAILURE;
END;

-- WHEN-NEW-FORM-INSTANCE
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.initialize('EXP_REPORT_TO_EXCEEL');
END;

-- KEY-COMMIT
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.save_document(NULL);
  COMMIT_FORM;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    MESSAGE('Save failed: ' || SQLERRM);
    RAISE FORM_TRIGGER_FAILURE;
END;

-- KEY-EXIT
BEGIN
  EXIT_FORM;
END;

-- WHEN-VALIDATE-RECORD
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.validate_before_save(NULL);
EXCEPTION
  WHEN OTHERS THEN
    MESSAGE('Validation failed: ' || SQLERRM);
    RAISE FORM_TRIGGER_FAILURE;
END;

-- WHEN-BUTTON-PRESSED: SAVE
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.save_document(NULL);
  COMMIT_FORM;
END;

-- WHEN-BUTTON-PRESSED: POST
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.post_document(NULL);
  COMMIT_FORM;
END;

-- WHEN-BUTTON-PRESSED: REVERSE
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.reverse_document(NULL);
  COMMIT_FORM;
END;

-- WHEN-BUTTON-PRESSED: PRINT
BEGIN
  RB_EXP_REPORT_TO_EXCEEL_5D757.print_document(NULL);
END;

-- ON-ERROR
BEGIN
  MESSAGE('Oracle Forms error: ' || ERROR_TYPE || '-' || TO_CHAR(ERROR_CODE));
  RAISE FORM_TRIGGER_FAILURE;
END;

-- Observed catalog indicators: procedures=0, triggers=0, tables=7, risks=none
