const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const crypto = require('crypto');
const db = new Proxy({}, { get(_target, property) { return require('./db')[property]; } });
const dbSetup = require('./db-setup');
const sessionContext = require('./session-context');
const commercialLicense = require('./commercial-license-core');
const businessOperations = require('./business-operations-core');
const accessDb = require('./access-db');
const accessRepo = require('./access-erp-repository');

let currentSession = null;
function requirePermission(permission) { if (!currentSession) throw new Error('يجب تسجيل الدخول أولاً.'); const granted = (currentSession.permissions || []).map(value => String(value).toUpperCase()); if (!granted.includes(String(permission).toUpperCase()) && !granted.includes('ALL') && !granted.includes('MANAGE_USERS')) throw new Error('لا تملك صلاحية تنفيذ هذه العملية.'); }
function enforceCommercialLicense(feature) {
  const raw = String(process.env.MIDO_LICENSE_JSON || '').trim();
  if (!raw) return { state: 'DEMO', reason: 'NO_LICENSE_CONFIGURED' };
  let license;
  try { license = JSON.parse(raw); } catch (_) { throw new Error('إعداد الترخيص التجاري غير صالح.'); }
  return commercialLicense.enforceEntitlement({ license, feature, currentUsers: 1, currentBranches: 1, options: { today: new Date().toISOString().slice(0, 10), publicKey: process.env.MIDO_LICENSE_PUBLIC_KEY || null } });
}
function registerDatabaseHandlers() {
  const accessConfig = payload => ({ filePath: payload.filePath || path.join(app.getPath('userData'), 'onyx-erp.accdb') });
  ipcMain.handle('db:setup-test', (_event, payload = {}) => { requirePermission('MANAGE_DATABASE'); return dbSetup.testConnection(payload); });
  ipcMain.handle('db:setup-inspect', (_event, payload = {}) => { requirePermission('MANAGE_DATABASE'); return dbSetup.inspectOracleSchema(payload); });
  ipcMain.handle('db:setup-initialize', (_event, payload = {}) => { requirePermission('MANAGE_DATABASE'); return dbSetup.initializeSchema(payload); });
  ipcMain.handle('db:test', async () => { try { return { connected: true, ...(await db.test()) }; } catch (error) { return { connected: false, reason: error.message }; } });
  ipcMain.handle('db:dashboard', () => { requirePermission('VIEW_DASHBOARD'); return db.dashboard(); });
  ipcMain.handle('db:accounts', (_event, payload = {}) => { requirePermission('VIEW_ACCOUNTS'); return db.accounts(payload.search || ''); });
  ipcMain.handle('db:modern-accounts', (_event, payload = {}) => { requirePermission('VIEW_ACCOUNTS'); return db.modernAccounts(payload.search || ''); });
  ipcMain.handle('db:create-account', async (_event, payload = {}) => { requirePermission('MANAGE_ACCOUNTS'); const result = await db.createModernAccount({ ...payload, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_ACCOUNT', entityType: 'ACCOUNT', entityId: result.accountId, afterValue: result }); return result; });
  ipcMain.handle('db:modern-contacts', (_event, payload = {}) => { requirePermission('VIEW_CONTACTS'); return db.modernContacts(payload.search || ''); });
  ipcMain.handle('db:create-contact', async (_event, payload = {}) => { requirePermission('MANAGE_CONTACTS'); const result = await db.createModernContact({ ...payload, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_CONTACT', entityType: 'CONTACT', entityId: result.contactId || result.code, afterValue: result }); return result; });
  ipcMain.handle('db:modern-items', (_event, payload = {}) => { requirePermission('VIEW_INVENTORY'); return db.modernItems(payload.search || ''); });
  ipcMain.handle('db:create-item', async (_event, payload = {}) => { requirePermission('MANAGE_INVENTORY'); const result = await db.createModernItem({ ...payload, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_ITEM', entityType: 'ITEM', entityId: result.itemId || result.code, afterValue: result }); return result; });
  ipcMain.handle('db:create-invoice', async (_event, payload = {}) => { requirePermission('CREATE_INVOICES'); requirePermission('POST_JOURNALS'); enforceCommercialLicense(payload.type === 'PURCHASE' ? 'PURCHASES' : 'INVOICING'); const result = await db.createModernInvoice({ ...payload, context: currentSession.context || {}, permissions: currentSession.permissions || [], userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'POST_INVOICE', entityType: 'INVOICE', entityId: result.invoiceId, afterValue: result }); return result; });
  ipcMain.handle('db:transition-invoice', async (_event, payload = {}) => { requirePermission(payload.action === 'POST' || payload.action === 'VOID' ? 'POST_JOURNALS' : 'CREATE_INVOICES'); const result = await db.transitionInvoice({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: `${payload.action}_INVOICE`, entityType: 'INVOICE', entityId: result.invoiceId, afterValue: result }); return result; });
  ipcMain.handle('inventory:warehouses', (_event, payload = {}) => { requirePermission('VIEW_INVENTORY'); return db.listWarehouses({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('inventory:movements', (_event, payload = {}) => { requirePermission('VIEW_INVENTORY'); return db.listStockMovements({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('invoices:list', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.listInvoices({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('receivables:payments:list', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.listReceivablePayments({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('receivables:aging', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.receivablesAgingReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('receivables:payment:create', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.createReceivablePayment({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_AR_PAYMENT', entityType: 'AR_PAYMENT', entityId: result.paymentId, afterValue: result }); return result; });
  ipcMain.handle('receivables:payment:post', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.postReceivablePayment({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'POST_AR_PAYMENT', entityType: 'AR_PAYMENT', entityId: result.paymentId, afterValue: result }); return result; });
  ipcMain.handle('cash-vouchers:list', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.listCashVouchers({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('cash-vouchers:create', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.createCashVoucher({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_CASH_VOUCHER', entityType: 'CASH_VOUCHER', entityId: result.voucherId, afterValue: result }); return result; });
  ipcMain.handle('cash-vouchers:update', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.updateCashVoucher({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'UPDATE_CASH_VOUCHER', entityType: 'CASH_VOUCHER', entityId: result.voucherId, afterValue: result }); return result; });
  ipcMain.handle('cash-vouchers:void', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.voidCashVoucher({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'VOID_CASH_VOUCHER', entityType: 'CASH_VOUCHER', entityId: result.voucherId, afterValue: result }); return result; });
  ipcMain.handle('expense-income:list', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.listExpenseIncome({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('expense-income:create', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.createExpenseIncome({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_EXPENSE_INCOME', entityType: payload.operationType || 'EXPENSE', entityId: result.operationId, afterValue: result }); return result; });
  ipcMain.handle('expense-income:update', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.updateExpenseIncome({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'UPDATE_EXPENSE_INCOME', entityType: payload.operationType || 'EXPENSE', entityId: result.operationId, afterValue: result }); return result; });
  ipcMain.handle('expense-income:void', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.voidExpenseIncome({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'VOID_EXPENSE_INCOME', entityType: payload.operationType || 'EXPENSE', entityId: result.operationId, afterValue: result }); return result; });
  ipcMain.handle('business:preview', (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const operation = String(payload.operation || '').toUpperCase(); if (operation === 'STOCK_MOVEMENT') return businessOperations.buildStockMovement(payload); if (operation === 'STOCK_TRANSFER') return businessOperations.buildStockTransfer(payload); if (operation === 'VOUCHER') return businessOperations.buildVoucher(payload); if (operation === 'EXPENSE') return businessOperations.buildExpense(payload); if (operation === 'INCOME') return businessOperations.buildIncome(payload); if (operation === 'ASSET') return businessOperations.registerAsset(payload); if (operation === 'DEPRECIATION') return businessOperations.calculateDepreciation(payload.asset, payload.months); throw new Error('عملية تجارية غير مدعومة.'); });
  ipcMain.handle('documents:create', async (_event, payload = {}) => { requirePermission(payload.documentType?.includes('ORDER') ? 'CREATE_ORDERS' : 'CREATE_INVOICES'); const result = await db.createTradeDocument({ ...payload, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_TRADE_DOCUMENT', entityType: payload.documentType || 'TRADE_DOCUMENT', entityId: result.documentId, afterValue: result }); return result; });
  ipcMain.handle('documents:list', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.listTradeDocuments(payload); });
  ipcMain.handle('documents:transition', async (_event, payload = {}) => { requirePermission(payload.nextStatus === 'POSTED' ? 'POST_JOURNALS' : 'CREATE_ORDERS'); return db.transitionTradeDocument({ ...payload, userId: currentSession.userId }); });
  ipcMain.handle('db:customers', (_event, payload = {}) => { requirePermission('VIEW_CONTACTS'); return db.customers(payload.search || ''); });
  ipcMain.handle('db:journal', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.journal(payload.limit || 50); });
  ipcMain.handle('reports:financial', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.financialReports(payload); });
  ipcMain.handle('reports:trial-balance', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.trialBalanceReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('reports:general-ledger', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.generalLedgerReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('reports:income-statement', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.incomeStatementReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('reports:balance-sheet', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.balanceSheetReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('reports:sales-purchase', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.salesPurchaseReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('reports:inventory-valuation', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.inventoryValuationReport({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('periods:list', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.listFiscalPeriods({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('periods:close:precheck', (_event, payload = {}) => { requirePermission('VIEW_REPORTS'); return db.precheckFiscalPeriodClose({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('periods:close:execute', async (_event, payload = {}) => { requirePermission('CLOSE_PERIOD'); const result = await db.closeFiscalPeriod({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CLOSE_PERIOD', entityType: 'FISCAL_PERIOD', entityId: result.periodId, afterValue: result }); return result; });
  ipcMain.handle('periods:reopen', async (_event, payload = {}) => { requirePermission('REOPEN_PERIOD'); const result = await db.reopenFiscalPeriod({ ...payload, context: currentSession.context || {}, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'REOPEN_PERIOD', entityType: 'FISCAL_PERIOD', entityId: result.periodId, afterValue: result }); return result; });
  ipcMain.handle('periods:close-history', (_event, payload = {}) => { requirePermission('VIEW_AUDIT_LOG'); return db.listPeriodCloseHistory({ ...payload, context: currentSession.context || {} }); });
  ipcMain.handle('db:create-journal', async (_event, payload = {}) => { requirePermission('POST_JOURNALS'); const result = await db.createModernJournal({ ...payload, userId: currentSession.userId }); await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'CREATE_JOURNAL', entityType: 'JOURNAL_ENTRY', entityId: result.entryId, afterValue: result }); return result; });
  ipcMain.handle('auth:current', () => currentSession);
  ipcMain.handle('auth:contexts', () => { if (!currentSession) throw new Error('يجب تسجيل الدخول أولاً.'); return db.listSessionContexts(currentSession.userId); });
  ipcMain.handle('auth:set-context', async (_event, payload = {}) => { if (!currentSession) throw new Error('يجب تسجيل الدخول أولاً.'); const selected = await db.setSessionContext(currentSession.userId, payload); currentSession = { ...currentSession, context: sessionContext.normalizeContext({ ...payload, languageCode: currentSession.languageCode, terminal: 'Electron' }), company: selected }; await db.recordAudit({ ...currentSession.context, userId: currentSession.userId, actionCode: 'SET_SESSION_CONTEXT', entityType: 'SESSION', entityId: currentSession.userId, afterValue: selected }); return currentSession; });
  ipcMain.handle('auth:login', async (_event, payload = {}) => { currentSession = await db.authenticate(payload.username, payload.password, { languageCode: 'ar', terminal: 'Electron' }); return currentSession; });
  ipcMain.handle('auth:logout', async () => { if (currentSession) { await db.recordAudit({ ...(currentSession.context || {}), userId: currentSession.userId, actionCode: 'LOGOUT', entityType: 'SESSION', entityId: currentSession.userId }); } currentSession = null; return true; });
  ipcMain.handle('admin:list-audit', (_event, payload = {}) => { requirePermission('VIEW_AUDIT_LOG'); return db.listAudit({ ...(currentSession.context || {}), ...payload }); });
  ipcMain.handle('admin:has-users', async () => { try { return (await db.listUsers()).length > 0; } catch (_) { return false; } });
  ipcMain.handle('admin:list-users', () => { requirePermission('MANAGE_USERS'); return db.listUsers(); });
  ipcMain.handle('admin:list-roles', () => { requirePermission('MANAGE_ROLES'); return db.listRoles(); });
  ipcMain.handle('admin:create-user', async (_event, payload = {}) => { const users = await db.listUsers(); if (users.length > 0) requirePermission('MANAGE_USERS'); const user = await db.createUser({ ...payload, actorUserId: currentSession?.userId }); if (users.length === 0) await db.assignRole(user.userId, 'ADMIN'); return user; });
  ipcMain.handle('admin:assign-role', (_event, payload = {}) => { requirePermission('MANAGE_USERS'); return db.assignRole(payload.userId, payload.roleCode, currentSession.userId); });
  ipcMain.handle('access:test', (_event, payload = {}) => accessDb.test(payload));
  ipcMain.handle('access:initialize', (_event, payload = {}) => accessDb.initialize(payload));
  ipcMain.handle('access:backup', (_event, payload = {}) => accessDb.backup(payload, payload.destination));
  ipcMain.handle('access:status', () => { const filePath = path.join(app.getPath('userData'), 'onyx-erp.accdb'); return { configured: require('fs').existsSync(filePath), filePath }; });
  ipcMain.handle('access:provision', async (_event, payload = {}) => { const filePath = payload.filePath || path.join(app.getPath('userData'), 'onyx-erp.accdb'); return accessDb.initialize({ ...payload, filePath }); });
  ipcMain.handle('access:list', (_event, payload = {}) => accessRepo.list(accessConfig(payload), payload.entity, payload.search));
  ipcMain.handle('access:create-account', (_event, payload = {}) => accessRepo.createAccount(accessConfig(payload), payload));
  ipcMain.handle('access:update-account', (_event, payload = {}) => accessRepo.updateAccount(accessConfig(payload), payload));
  ipcMain.handle('access:delete-account', (_event, payload = {}) => accessRepo.deleteAccount(accessConfig(payload), payload));
  ipcMain.handle('access:create-contact', (_event, payload = {}) => accessRepo.createContact(accessConfig(payload), payload));
  ipcMain.handle('access:update-contact', (_event, payload = {}) => accessRepo.updateContact(accessConfig(payload), payload));
  ipcMain.handle('access:delete-contact', (_event, payload = {}) => accessRepo.deleteContact(accessConfig(payload), payload));
  ipcMain.handle('access:create-item', (_event, payload = {}) => accessRepo.createItem(accessConfig(payload), payload));
  ipcMain.handle('access:update-item', (_event, payload = {}) => accessRepo.updateItem(accessConfig(payload), payload));
  ipcMain.handle('access:delete-item', (_event, payload = {}) => accessRepo.deleteItem(accessConfig(payload), payload));
  ipcMain.handle('access:create-invoice', (_event, payload = {}) => accessRepo.createInvoice(accessConfig(payload), payload));
  ipcMain.handle('access:post-invoice', (_event, payload = {}) => accessRepo.postInvoice(accessConfig(payload), payload));
  ipcMain.handle('access:void-invoice', (_event, payload = {}) => accessRepo.voidInvoice(accessConfig(payload), payload));
  ipcMain.handle('access:create-journal', (_event, payload = {}) => accessRepo.createJournal(accessConfig(payload), payload));
  ipcMain.handle('access:update-setting', (_event, payload = {}) => accessRepo.updateSetting(accessConfig(payload), payload));
  ipcMain.handle('access:update-company', (_event, payload = {}) => accessRepo.updateCompany(accessConfig(payload), payload));
  ipcMain.handle('access:update-branch', (_event, payload = {}) => accessRepo.updateBranch(accessConfig(payload), payload));
  ipcMain.handle('access:update-fiscal-year', (_event, payload = {}) => accessRepo.updateFiscalYear(accessConfig(payload), payload));
}
function createWindow() {
  const window = new BrowserWindow({ width: 1440, height: 920, minWidth: 1120, minHeight: 720, backgroundColor: '#f6f8fb', title: 'أونكس المحاسبي', webPreferences: { contextIsolation: true, nodeIntegration: false, sandbox: true, preload: path.join(__dirname, 'preload.js') } });
  window.loadFile(path.join(__dirname, 'index.html'));
}
app.whenReady().then(() => { registerDatabaseHandlers(); createWindow(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) createWindow(); }); });
app.on('before-quit', async () => { await db.close(); });
app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
