-- أونكس المحاسبي | Oracle foundation schema
-- يدعم شاشة ERP_LOGIN: الشركة، الفرع، السنة، اللغة، الصلاحيات، وسجل الدخول.
-- ملاحظة: لا يتم تجاوز التاريخ المحاسبي بشكل غير مراقب؛ يتم التحكم به عبر الفترة المالية وصلاحية BACKDATE_POSTING.

CREATE TABLE onyx_company (
  company_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_code      VARCHAR2(30) NOT NULL UNIQUE,
  company_name_ar   VARCHAR2(200) NOT NULL,
  company_name_en   VARCHAR2(200),
  base_currency     VARCHAR2(3) DEFAULT 'SAR' NOT NULL,
  active_flag       NUMBER(1) DEFAULT 1 NOT NULL,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE onyx_branch (
  branch_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id        NUMBER NOT NULL REFERENCES onyx_company(company_id),
  branch_code       VARCHAR2(30) NOT NULL,
  branch_name_ar    VARCHAR2(200) NOT NULL,
  branch_name_en    VARCHAR2(200),
  active_flag       NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT uq_onyx_branch UNIQUE (company_id, branch_code)
);

CREATE TABLE onyx_fiscal_year (
  fiscal_year_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id        NUMBER NOT NULL REFERENCES onyx_company(company_id),
  fiscal_year       NUMBER(4) NOT NULL,
  start_date        DATE NOT NULL,
  end_date          DATE NOT NULL,
  status_code       VARCHAR2(12) DEFAULT 'OPEN' NOT NULL,
  CONSTRAINT ck_onyx_fy_dates CHECK (end_date >= start_date),
  CONSTRAINT ck_onyx_fy_status CHECK (status_code IN ('OPEN','CLOSED','LOCKED')),
  CONSTRAINT uq_onyx_fy UNIQUE (company_id, fiscal_year)
);

CREATE TABLE onyx_user (
  user_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username          VARCHAR2(80) NOT NULL UNIQUE,
  display_name_ar   VARCHAR2(200) NOT NULL,
  password_hash     VARCHAR2(255) NOT NULL,
  language_code     VARCHAR2(10) DEFAULT 'ar' NOT NULL,
  active_flag       NUMBER(1) DEFAULT 1 NOT NULL,
  locked_until      TIMESTAMP,
  failed_attempts   NUMBER DEFAULT 0 NOT NULL,
  last_login_at     TIMESTAMP,
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE onyx_role (
  role_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code         VARCHAR2(50) NOT NULL UNIQUE,
  role_name_ar      VARCHAR2(150) NOT NULL,
  active_flag       NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE onyx_permission (
  permission_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission_code   VARCHAR2(80) NOT NULL UNIQUE,
  permission_name_ar VARCHAR2(200) NOT NULL
);

CREATE TABLE onyx_user_role (
  user_id           NUMBER NOT NULL REFERENCES onyx_user(user_id),
  role_id           NUMBER NOT NULL REFERENCES onyx_role(role_id),
  CONSTRAINT pk_onyx_user_role PRIMARY KEY (user_id, role_id)
);

CREATE TABLE onyx_role_permission (
  role_id           NUMBER NOT NULL REFERENCES onyx_role(role_id),
  permission_id     NUMBER NOT NULL REFERENCES onyx_permission(permission_id),
  CONSTRAINT pk_onyx_role_perm PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE onyx_user_scope (
  user_id           NUMBER NOT NULL REFERENCES onyx_user(user_id),
  company_id        NUMBER NOT NULL REFERENCES onyx_company(company_id),
  branch_id         NUMBER NOT NULL REFERENCES onyx_branch(branch_id),
  default_year_id   NUMBER REFERENCES onyx_fiscal_year(fiscal_year_id),
  CONSTRAINT pk_onyx_user_scope PRIMARY KEY (user_id, company_id, branch_id)
);

CREATE TABLE onyx_login_history (
  login_history_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           NUMBER REFERENCES onyx_user(user_id),
  username_entered  VARCHAR2(80) NOT NULL,
  company_id        NUMBER REFERENCES onyx_company(company_id),
  branch_id         NUMBER REFERENCES onyx_branch(branch_id),
  fiscal_year_id    NUMBER REFERENCES onyx_fiscal_year(fiscal_year_id),
  language_code     VARCHAR2(10),
  terminal_name     VARCHAR2(255),
  login_type        VARCHAR2(20) NOT NULL,
  failure_reason    VARCHAR2(200),
  login_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  logout_at         TIMESTAMP
);

CREATE TABLE onyx_accounting_control (
  company_id             NUMBER PRIMARY KEY REFERENCES onyx_company(company_id),
  allow_backdate_flag    NUMBER(1) DEFAULT 0 NOT NULL,
  backdate_days_limit    NUMBER DEFAULT 0 NOT NULL,
  allow_future_date_flag NUMBER(1) DEFAULT 0 NOT NULL,
  current_business_date  DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  period_lock_date       DATE,
  updated_at             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO onyx_permission(permission_code, permission_name_ar) VALUES ('LOGIN', 'تسجيل الدخول');
INSERT INTO onyx_permission(permission_code, permission_name_ar) VALUES ('BACKDATE_POSTING', 'ترحيل بتاريخ سابق');
INSERT INTO onyx_permission(permission_code, permission_name_ar) VALUES ('OPEN_FISCAL_PERIOD', 'فتح فترة مالية');
INSERT INTO onyx_permission(permission_code, permission_name_ar) VALUES ('CLOSE_FISCAL_PERIOD', 'إغلاق فترة مالية');
INSERT INTO onyx_permission(permission_code, permission_name_ar) VALUES ('MANAGE_USERS', 'إدارة المستخدمين والصلاحيات');
INSERT INTO onyx_permission(permission_code, permission_name_ar) VALUES ('VIEW_AUDIT_LOG', 'عرض سجل التدقيق');
COMMIT;

CREATE OR REPLACE FUNCTION onyx_can_post_date(
  p_user_id     IN NUMBER,
  p_company_id  IN NUMBER,
  p_post_date   IN DATE
) RETURN NUMBER IS
  v_business_date DATE;
  v_lock_date DATE;
  v_allow_backdate NUMBER;
  v_backdate_limit NUMBER;
  v_allow_future NUMBER;
  v_has_perm NUMBER;
BEGIN
  SELECT current_business_date, period_lock_date, allow_backdate_flag,
         backdate_days_limit, allow_future_date_flag
    INTO v_business_date, v_lock_date, v_allow_backdate,
         v_backdate_limit, v_allow_future
    FROM onyx_accounting_control
   WHERE company_id = p_company_id;

  SELECT COUNT(*) INTO v_has_perm
    FROM onyx_user_role ur
    JOIN onyx_role_permission rp ON rp.role_id = ur.role_id
    JOIN onyx_permission p ON p.permission_id = rp.permission_id
   WHERE ur.user_id = p_user_id AND p.permission_code = 'BACKDATE_POSTING';

  IF v_lock_date IS NOT NULL AND TRUNC(p_post_date) <= TRUNC(v_lock_date) THEN
    RETURN 0;
  ELSIF TRUNC(p_post_date) < TRUNC(v_business_date) THEN
    IF v_allow_backdate = 1 AND v_has_perm > 0
       AND TRUNC(v_business_date) - TRUNC(p_post_date) <= v_backdate_limit THEN
      RETURN 1;
    END IF;
    RETURN 0;
  ELSIF TRUNC(p_post_date) > TRUNC(v_business_date) THEN
    RETURN CASE WHEN v_allow_future = 1 THEN 1 ELSE 0 END;
  END IF;
  RETURN 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN RETURN 0;
END;
/


-- سجل تدقيق عام للعمليات الحساسة، منفصل عن سجل محاولات الدخول.
CREATE TABLE onyx_audit_log (
  audit_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           NUMBER REFERENCES onyx_user(user_id),
  company_id        NUMBER REFERENCES onyx_company(company_id),
  branch_id         NUMBER REFERENCES onyx_branch(branch_id),
  fiscal_year_id    NUMBER REFERENCES onyx_fiscal_year(fiscal_year_id),
  action_code       VARCHAR2(80) NOT NULL,
  entity_type       VARCHAR2(80) NOT NULL,
  entity_id         VARCHAR2(80),
  before_value      CLOB,
  after_value       CLOB,
  reason            VARCHAR2(500),
  terminal_name     VARCHAR2(255),
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX ix_onyx_audit_scope ON onyx_audit_log(company_id, branch_id, fiscal_year_id, created_at);
CREATE INDEX ix_onyx_audit_action ON onyx_audit_log(action_code, created_at);
COMMIT;
