import type { WindowAction, WindowKind, WindowRecord } from "./WindowManager";

export type LegacyField = { id: string; label: string; type: "text" | "date" | "number" | "select" | "password"; required?: boolean; evidence: "extracted" | "inferred" };
export type LegacyWindowContract = WindowRecord & { module: string; kind: WindowKind; fields: LegacyField[]; actions: WindowAction[]; source: { form: string; namespace: string; libraries: string[]; tables: string[]; procedures: string[] }; notes: string };

const commonActions: WindowAction[] = ["new", "save", "delete", "query", "print", "cancel", "help"];
const base = (id: string, label: string, module: string, kind: WindowKind, namespace: string, fields: LegacyField[], tables: string[], procedures: string[], notes: string): LegacyWindowContract => ({ id, label, module, kind, formName: `${id}.fmx`, fields, actions: commonActions, source: { form: `${id}.fmx`, namespace, libraries: ["LYSERP_LIB", "GEN_PKG", "VIEW_BTN", "SCREEN_BTN", "PRINT_DOC_BTN", "CANCEL_BTN"], tables, procedures }, notes });
const text = (id: string, label: string, evidence: LegacyField["evidence"] = "extracted", required = false): LegacyField => ({ id, label, type: "text", evidence, required });
const number = (id: string, label: string, evidence: LegacyField["evidence"] = "inferred", required = false): LegacyField => ({ id, label, type: "number", evidence, required });
const date = (id: string, label: string): LegacyField => ({ id, label, type: "date", evidence: "inferred" });
const select = (id: string, label: string): LegacyField => ({ id, label, type: "select", evidence: "inferred" });

export const legacyContracts: Record<string, LegacyWindowContract> = {
  ERP_LOGIN: base("ERP_LOGIN", "تسجيل الدخول", "admin", "transaction", "NSPC1", [text("USR", "اسم المستخدم", "extracted", true), { id: "PASSWORD", label: "كلمة المرور", type: "password", evidence: "extracted", required: true }, select("CMP_NO", "الشركة"), select("BRN_NO", "الفرع"), select("PRD_NO", "الفترة"), select("LANG_NO", "اللغة")], ["ALL_USERS", "S_BRN", "S_YS_CMP", "S_PRD_DTL", "PRIVILEGE", "IAS_SYS", "IAS_PARA_GEN"], ["CHECK_MSG_USR", "CHECK_NOTE_USR", "CALL_FAV_SCR", "CALL_OBJCT_PKG", "CALL_SCR", "DECRYPT_PASS", "CHECK_USER_TRMNAL", "SET_DIR_PRC", "EXIT_PRC"], "يعكس عناصر تسجيل الدخول والسياق والامتيازات الظاهرة في FMX؛ أسماء بعض حقول الاختيار مستنتجة من جداول النظام.") ,
  ERP_DBA: base("ERP_DBA", "إدارة النظام", "admin", "transaction", "NSPC1", [text("USR", "المستخدم", "extracted", true), text("USR_NAME", "اسم المستخدم", "inferred"), select("CMP_NO", "الشركة"), select("BRN_NO", "الفرع"), select("PRIVILEGE", "مجموعة الصلاحيات"), select("LANG_NO", "اللغة")], ["ALL_USERS", "PRIVILEGE", "S_BRN_USR_PRIV", "S_YS_CMP", "IAS_FAVORITE_SCR", "IAS_MSG_USER", "IAS_NOTES_USER"], ["CALL_OBJCT_PKG", "CALL_FAV_SCR", "CALL_SCR", "ALTER_PASS", "CHECK_USER_TRMNAL", "EXIT_PRC"], "عقد إداري مبني على كائنات المستخدمين والامتيازات والتنقل المضمنة في ERP_DBA.fmx.") ,
  GLST001: base("GLST001", "دليل الحسابات", "finance", "transaction", "NSPC6", [text("A_CODE", "رمز الحساب", "extracted", true), text("A_NAME", "اسم الحساب", "extracted", true), text("A_E_NAME", "الاسم الإنجليزي", "extracted"), select("A_GROUPING", "مجموعة الحساب"), select("A_TYPE", "نوع الحساب"), select("A_CY", "العملة"), text("CC_CODE", "مركز التكلفة", "inferred"), { id: "ACTIVE", label: "نشط", type: "select", evidence: "inferred" }], ["ACCOUNT", "ACCOUNT_CURR", "ACCOUNT_TYPES", "ACCOUNT_REPORT_TYPE", "IAS_ACCOUNT_CC", "IAS_ACCOUNT_PJ", "COST_CENTERS", "IAS_PARA_GEN"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "العقد يطابق دورة دليل الحسابات القياسية: إضافة/تعديل/حذف/استعلام مع تحقق قبل الحفظ.") ,
  GLST002: base("GLST002", "القيد اليومي", "finance", "transaction", "NSPC7", [text("DOC_NO", "رقم القيد", "inferred", true), date("DOC_DATE", "تاريخ القيد"), select("DOC_TYP", "نوع القيد"), text("A_CODE", "الحساب", "extracted", true), number("DEBIT", "مدين"), number("CREDIT", "دائن"), text("REMARKS", "البيان", "inferred"), select("CC_CODE", "مركز التكلفة")], ["GLS_VCHR_MST_ACCNT", "GLS_BNK_CHQ_MST", "GLS_RQ_VCHR_MST_ACCNT", "IAS_DOCJV_TYPE_SYSTEMS_MST", "ACCOUNT", "ACCOUNT_CURR", "IAS_ACCOUNT_CC"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ACY_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "العقد يطابق عناصر القيد والترحيل المحاسبي الظاهرة في FMX؛ توازن المدين والدائن يحتاج ربط خدمة الترحيل.") ,
  INVT003: base("INVT003", "بطاقة الصنف", "inventory", "transaction", "NSPC9", [text("I_CODE", "رمز الصنف", "extracted", true), text("I_NAME", "اسم الصنف", "extracted", true), text("I_E_NAME", "الاسم الإنجليزي", "extracted"), text("I_DESC", "الوصف", "extracted"), select("GROUP_NO", "مجموعة الصنف"), select("ITEM_TYPE", "نوع الصنف"), select("U_CODE", "وحدة القياس"), select("W_CODE", "المستودع"), number("NEW_COST", "التكلفة", "extracted"), text("BARCODE", "الباركود", "inferred")], ["IAS_ITM_MST", "IAS_ITM_DTL", "IAS_ITEM_MST_TMP", "IAS_ITEM_DTL_TMP", "IAS_ITEM_PRICE", "IAS_ITEM_SERIAL", "IAS_ITEM_SERIALNO", "ITEMS_COSTING", "IAS_ITM_BARCODE", "IAS_BATCH_NO"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "GET_ITEM_INFO", "CHECK_DUPLICATE_ITM", "CALC_WTAVG_COST", "GENERATE_ITM_BARCODE", "EXIT_PROC"], "عقد الصنف يضم تعريف الصنف والتكلفة والباركود والرقم التسلسلي، وهي عناصر مدعومة مباشرة من مراجع الجداول والبرامج في FMX.") ,
  APST003: base("APST003", "فاتورة المشتريات", "purchasing", "transaction", "NSPC23", [text("GR_NO", "رقم الاستلام", "inferred", true), date("GR_DATE", "تاريخ الاستلام"), select("V_CODE", "المورد"), select("W_CODE", "المستودع"), text("I_CODE", "الصنف", "extracted", true), number("QTY", "الكمية", "inferred", true), number("PRICE", "السعر", "inferred"), number("TAX_AMT", "الضريبة", "inferred"), text("BATCH_NO", "رقم التشغيلة", "extracted")], ["GR_DETAIL", "GRN_DETAIL", "IAS_AP_CNTRCT_MST", "IAS_AP_CNTRCT_DTL", "IAS_ITEM_MST_TMP", "IAS_ITEM_PRICE", "IAS_BATCH_NO", "IAS_ITM_MST", "IAS_ITM_DTL", "ACCOUNT_CURR"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "CHECK_DUPLICATE", "CHECK_ITEM", "CHECK_REQST_QTY", "CALC_WTAVG", "SAVE_PROC", "PRINT_PROC", "EXIT_PROC"], "عقد مشتريات فعلي أولي؛ يتضمن رأس المستند والتفاصيل والمورد والتكلفة والتشغيلة والتحقق قبل الحفظ.") ,
  ARST003: base("ARST003", "تعريف العملاء", "sales", "transaction", "NSPC8", [text("C_CODE", "رمز العميل", "extracted", true), text("C_NAME", "اسم العميل", "extracted", true), text("C_E_NAME", "الاسم الإنجليزي", "extracted"), text("ADDRESS", "العنوان", "inferred"), text("TEL", "الهاتف", "inferred"), select("A_CODE", "حساب العميل"), select("A_CY", "عملة الحساب"), text("TAX_NO", "الرقم الضريبي", "inferred"), { id: "ACTIVE", label: "نشط", type: "select", evidence: "inferred" }], ["CUSTOMER", "CUSTOMER_CURR", "IAS_PARA_AR", "IAS_PARA_GEN", "IAS_ITEM_PRICE", "ACCOUNT_CURR", "IAS_BILL_MST", "IAS_BILL_DTL"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "CHECK_DUPLICATE", "CHECK_CST_VNDR_CSH", "EXIT_PROC"], "عقد العملاء يربط بطاقة العميل بالحساب والعملة وإعدادات AR، مع تحقق التكرار والصلاحيات قبل الحفظ.") ,
};

export function getLegacyContract(id: string): LegacyWindowContract | undefined { return legacyContracts[id.replace(/\.fmx$/i, "").toUpperCase()]; }
