import type { WindowAction, WindowKind, WindowRecord } from "./WindowManager";

export type LegacyField = { id: string; label: string; type: "text" | "date" | "number" | "select" | "password"; required?: boolean; evidence: "extracted" | "inferred" };
export type LegacyWindowContract = WindowRecord & { module: string; kind: WindowKind; fields: LegacyField[]; actions: WindowAction[]; source: { form: string; namespace: string; libraries: string[]; tables: string[]; procedures: string[] }; notes: string };

const commonActions: WindowAction[] = ["new", "save", "delete", "query", "print", "cancel", "help"];
const base = (id: string, label: string, module: string, kind: WindowKind, namespace: string, fields: LegacyField[], tables: string[], procedures: string[], notes: string): LegacyWindowContract => ({ id, label, module, kind, formName: `${id}.fmx`, fields, actions: commonActions, source: { form: `${id}.fmx`, namespace, libraries: ["LYSERP_LIB", "GEN_PKG", "VIEW_BTN", "SCREEN_BTN", "PRINT_DOC_BTN", "CANCEL_BTN"], tables, procedures }, notes });
const text = (id: string, label: string, evidence: LegacyField["evidence"] = "extracted", required = false): LegacyField => ({ id, label, type: "text", evidence, required });
const number = (id: string, label: string, evidence: LegacyField["evidence"] = "inferred", required = false): LegacyField => ({ id, label, type: "number", evidence, required });
const date = (id: string, label: string): LegacyField => ({ id, label, type: "date", evidence: "inferred" });
const select = (id: string, label: string): LegacyField => ({ id, label, type: "select", evidence: "inferred" });

export const legacyContracts: Record<string, LegacyWindowContract> = {
  ERP_LOGIN: base("ERP_LOGIN", "تسجيل الدخول", "admin", "transaction", "NSPC1", [text("USR", "اسم المستخدم", "extracted", true), { id: "PASSWORD", label: "كلمة المرور", type: "password", evidence: "extracted", required: true }, select("CMP_NO", "الشركة"), select("BRN_NO", "الفرع"), select("PRD_NO", "الفترة"), select("LANG_NO", "اللغة")], ["ALL_USERS", "S_BRN", "S_YS_CMP", "S_PRD_DTL", "PRIVILEGE", "IAS_SYS", "IAS_PARA_GEN"], ["CHECK_MSG_USR", "CHECK_NOTE_USR", "CALL_FAV_SCR", "CALL_OBJCT_PKG", "CALL_SCR", "DECRYPT_PASS", "CHECK_USER_TRMNAL", "SET_DIR_PRC", "EXIT_PRC"], "يعكس عناصر تسجيل الدخول والسياق والامتيازات الظاهرة في FMX؛ أسماء بعض حقول الاختيار مستنتجة من جداول النظام.") ,
  ERP_DBA: base("ERP_DBA", "إدارة النظام", "admin", "transaction", "NSPC1", [text("USR", "المستخدم", "extracted", true), text("USR_NAME", "اسم المستخدم", "inferred"), select("CMP_NO", "الشركة"), select("BRN_NO", "الفرع"), select("PRIVILEGE", "مجموعة الصلاحيات"), select("LANG_NO", "اللغة")], ["ALL_USERS", "PRIVILEGE", "S_BRN_USR_PRIV", "S_YS_CMP", "IAS_FAVORITE_SCR", "IAS_MSG_USER", "IAS_NOTES_USER"], ["CALL_OBJCT_PKG", "CALL_FAV_SCR", "CALL_SCR", "ALTER_PASS", "CHECK_USER_TRMNAL", "EXIT_PRC"], "عقد إداري مبني على كائنات المستخدمين والامتيازات والتنقل المضمنة في ERP_DBA.fmx.") ,
  GLST001: base("GLST001", "دليل الحسابات", "finance", "transaction", "NSPC6", [text("A_CODE", "رمز الحساب", "extracted", true), text("A_NAME", "اسم الحساب", "extracted", true), text("A_E_NAME", "الاسم الإنجليزي", "extracted"), select("A_GROUPING", "مجموعة الحساب"), select("A_TYPE", "نوع الحساب"), select("A_CY", "العملة"), text("CC_CODE", "مركز التكلفة", "inferred"), { id: "ACTIVE", label: "نشط", type: "select", evidence: "inferred" }], ["ACCOUNT", "ACCOUNT_CURR", "ACCOUNT_TYPES", "ACCOUNT_REPORT_TYPE", "IAS_ACCOUNT_CC", "IAS_ACCOUNT_PJ", "COST_CENTERS", "IAS_PARA_GEN"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "العقد يطابق دورة دليل الحسابات القياسية: إضافة/تعديل/حذف/استعلام مع تحقق قبل الحفظ.") ,
  GLST002: base("GLST002", "القيد اليومي", "finance", "transaction", "NSPC7", [text("DOC_NO", "رقم القيد", "inferred", true), date("DOC_DATE", "تاريخ القيد"), select("DOC_TYP", "نوع القيد"), text("A_CODE", "الحساب", "extracted", true), number("DEBIT", "مدين"), number("CREDIT", "دائن"), text("REMARKS", "البيان", "inferred"), select("CC_CODE", "مركز التكلفة")], ["GLS_VCHR_MST_ACCNT", "GLS_BNK_CHQ_MST", "GLS_RQ_VCHR_MST_ACCNT", "IAS_DOCJV_TYPE_SYSTEMS_MST", "ACCOUNT", "ACCOUNT_CURR", "IAS_ACCOUNT_CC"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ACY_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "العقد يطابق عناصر القيد والترحيل المحاسبي الظاهرة في FMX؛ توازن المدين والدائن يحتاج ربط خدمة الترحيل.") ,
  INVT003: base("INVT003", "بطاقة الصنف", "inventory", "transaction", "NSPC9", [text("I_CODE", "رمز الصنف", "extracted", true), text("I_NAME", "اسم الصنف", "extracted", true), text("I_E_NAME", "الاسم الإنجليزي", "extracted"), text("I_DESC", "الوصف", "extracted"), select("GROUP_NO", "مجموعة الصنف"), select("ITEM_TYPE", "نوع الصنف"), select("U_CODE", "وحدة القياس"), select("W_CODE", "المستودع"), number("NEW_COST", "التكلفة", "extracted"), text("BARCODE", "الباركود", "inferred")], ["IAS_ITM_MST", "IAS_ITM_DTL", "IAS_ITEM_MST_TMP", "IAS_ITEM_DTL_TMP", "IAS_ITEM_PRICE", "IAS_ITEM_SERIAL", "IAS_ITEM_SERIALNO", "ITEMS_COSTING", "IAS_ITM_BARCODE", "IAS_BATCH_NO"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "GET_ITEM_INFO", "CHECK_DUPLICATE_ITM", "CALC_WTAVG_COST", "GENERATE_ITM_BARCODE", "EXIT_PROC"], "عقد الصنف يضم تعريف الصنف والتكلفة والباركود والرقم التسلسلي، وهي عناصر مدعومة مباشرة من مراجع الجداول والبرامج في FMX.") ,
  APST003: base("APST003", "فاتورة المشتريات", "purchasing", "transaction", "NSPC23", [text("GR_NO", "رقم الاستلام", "inferred", true), date("GR_DATE", "تاريخ الاستلام"), select("V_CODE", "المورد"), select("W_CODE", "المستودع"), text("I_CODE", "الصنف", "extracted", true), number("QTY", "الكمية", "inferred", true), number("PRICE", "السعر", "inferred"), number("TAX_AMT", "الضريبة", "inferred"), text("BATCH_NO", "رقم التشغيلة", "extracted")], ["GR_DETAIL", "GRN_DETAIL", "IAS_AP_CNTRCT_MST", "IAS_AP_CNTRCT_DTL", "IAS_ITEM_MST_TMP", "IAS_ITEM_PRICE", "IAS_BATCH_NO", "IAS_ITM_MST", "IAS_ITM_DTL", "ACCOUNT_CURR"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "CHECK_DUPLICATE", "CHECK_ITEM", "CHECK_REQST_QTY", "CALC_WTAVG", "SAVE_PROC", "PRINT_PROC", "EXIT_PROC"], "عقد مشتريات فعلي أولي؛ يتضمن رأس المستند والتفاصيل والمورد والتكلفة والتشغيلة والتحقق قبل الحفظ.") ,
  ARST003: base("ARST003", "تعريف العملاء", "sales", "transaction", "NSPC8", [text("C_CODE", "رمز العميل", "extracted", true), text("C_NAME", "اسم العميل", "extracted", true), text("C_E_NAME", "الاسم الإنجليزي", "extracted"), text("ADDRESS", "العنوان", "inferred"), text("TEL", "الهاتف", "inferred"), select("A_CODE", "حساب العميل"), select("A_CY", "عملة الحساب"), text("TAX_NO", "الرقم الضريبي", "inferred"), { id: "ACTIVE", label: "نشط", type: "select", evidence: "inferred" }], ["CUSTOMER", "CUSTOMER_CURR", "IAS_PARA_AR", "IAS_PARA_GEN", "IAS_ITEM_PRICE", "ACCOUNT_CURR", "IAS_BILL_MST", "IAS_BILL_DTL"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "CHECK_DUPLICATE", "CHECK_CST_VNDR_CSH", "EXIT_PROC"], "عقد العملاء يربط بطاقة العميل بالحساب والعملة وإعدادات AR، مع تحقق التكرار والصلاحيات قبل الحفظ.") ,
  ARST004: base("ARST004", "فاتورة المبيعات", "sales", "transaction", "NSPC10", [text("DOC_NO", "رقم الفاتورة", "inferred", true), date("DOC_DATE", "تاريخ الفاتورة"), select("C_CODE", "العميل"), select("W_CODE", "المستودع"), text("I_CODE", "الصنف", "extracted", true), number("QTY", "الكمية", "inferred", true), number("PRICE", "السعر", "inferred"), number("DISC_AMT", "الخصم", "extracted"), number("TAX_AMT", "الضريبة", "inferred"), select("PAY_TYPE", "طريقة الدفع")], ["IAS_BILL_MST", "IAS_BILL_DTL", "IAS_BILL_MST_ADD_DISC", "IAS_BILL_DTL_ADD_DISC", "CUSTOMER", "IAS_ITM_MST", "IAS_ITM_WCODE", "IAS_POST_MST", "IAS_POST_DTL", "IAS_PARA_AR", "IAS_PARA_GL", "IAS_PARA_POS"], ["WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "CHECK_DUPLICATE", "CHECK_ITEM", "CHECK_QTY_RT_OUTGOING", "CHECK_PREVIOUS_MOVEMENT", "INSTALL_BILLS_PRC", "POSTION", "EXIT_PROC"], "عقد فاتورة المبيعات يربط رأس الفاتورة وتفاصيلها والمخزون والخصم والضريبة وأثر الترحيل.") ,
  ERP_DBA_DFLT_DATA: base("ERP_DBA_DFLT_DATA", "البيانات الافتراضية للنظام", "admin", "transaction", "NSPC2", [select("CMP_NO", "الشركة"), select("BRN_NO", "الفرع"), select("PRD_NO", "الفترة"), select("DOC_TYP", "نوع المستند"), select("A_CODE", "الحساب الافتراضي"), select("W_CODE", "المستودع الافتراضي"), { id: "USE_INV_ONLY", label: "المخزون فقط", type: "select", evidence: "extracted" }, { id: "USE_GL_ONLY", label: "الحسابات فقط", type: "select", evidence: "extracted" }, { id: "USE_ALERT_SYSTEM", label: "نظام التنبيهات", type: "select", evidence: "extracted" }], ["S_YS_CMP", "S_BRN", "ALL_BRANCHES", "IAS_PARA_GEN", "IAS_PARA_GL", "IAS_PARA_INV", "IAS_PARA_AP", "IAS_PARA_AR", "S_FLAGS", "FORM_DETAIL", "FORM_DE"], ["INSRT_DEF_DATA_PRC1", "INSRT_DEF_DATA_PRC2", "INSRT_DEF_DATA_PRC3", "CALL_IINSRT_ALL_FLGS_LOV", "INSERT_ONLINE_PRC", "INSRT_SFLAGS_PRC", "INSERT_LABELS", "LOGIN_PRC"], "عقد إعداد البيانات الافتراضية يعتمد على حزم إدخال إعدادات الوحدات ويُنفذ عند تهيئة الشركة والفرع.") ,
  ERP_JOURNAL: base("ERP_JOURNAL", "سجل العمليات والتدقيق", "admin", "inquiry", "NSPC1", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("USR", "المستخدم"), select("FORM_NO", "النافذة"), text("DOC_NO", "رقم المستند", "inferred"), select("ACTION", "نوع العملية")], ["IAS_TRACE_LGN_NOTE", "IAS_USR_LGN_HSTRY", "IAS_MSG_USER", "IAS_MSG_USER_DTL", "USER_OBJECTS", "USER_CONSTRAINTS"], ["CALL_SCR", "CALL_REP", "CHECK_MSG_USR", "CHECK_NOTE_USR", "EXIT_PRC"], "عقد استعلامي لسجل العمليات والتدقيق؛ الحقول الزمنية والمستخدم والنافذة مستندة إلى جداول التتبع والـForms المرجعية.") ,
  GLST004: base("GLST004", "السندات والقيود المالية", "finance", "transaction", "NSPC2", [text("DOC_NO", "رقم السند", "inferred", true), date("DOC_DATE", "تاريخ السند"), select("DOC_TYP", "نوع السند"), select("A_CODE", "الحساب"), number("AMT", "المبلغ"), select("CASH_ACCOUNT", "حساب النقدية"), text("REMARKS", "البيان", "inferred"), select("CC_CODE", "مركز التكلفة")], ["GLS_VCHR_MST_ACCNT", "GLS_RQ_VCHR_MST_ACCNT", "IAS_RQ_VCHR_MST", "IAS_RQ_VCHR_DTL", "IAS_PYMNT_DTL", "IAS_CASH_AT_BANK_DTL", "IAS_CASH_IN_HAND_DTL", "IAS_POST_DTL", "IAS_POST_MST", "ACCOUNT"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ACY_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "عقد السندات المالية يربط السندات المطلوبة والقيود النقدية وحسابات البنك/الصندوق مع دورة الحفظ والترحيل.") ,
  MRPACS004: base("MRPACS004", "إعدادات التخطيط والتصنيع", "mrp", "transaction", "NSPC1", [select("CMP_NO", "الشركة"), select("BRN_NO", "الفرع"), select("MRP_ONX_VERSION", "إصدار MRP"), select("MRP_SFC_USE_ITEM_PART", "استخدام أجزاء الصنف"), select("BRANCH_USER", "مستخدم الفرع"), select("MRP_SGS_GENERAL_PARAMETARS", "إعدادات التخطيط"), text("BOM_CODE", "رمز قائمة المواد", "inferred"), number("QTY", "الكمية", "inferred")], ["MRP_PCM_MRP_ONX_BRNCH", "MRP_SGS_GENERAL_PARAMETARS", "WM_INSTALLATION", "BOM", "BOMS", "ASSEMBLY", "C_ITEMS", "DEMAND", "ACTUAL_QTY", "DATABASE"], ["CHK_BRN_PARAMTRS_PRC", "DBA_CONST_SCRIPT", "DBA_PKG_MRP1", "DBA_PKG_MRP2", "DBA_PKG_BOM1", "DBA_PKG_BOM2", "DBA_PKG_MPS1", "DBA_PKG_MPS2", "DBA_PKG_PCM1", "DBA_PKG_PCM2", "MRP_DBS_PKG"], "عقد إعداد MRP مستخرج من استعلامات الإصدار والفرع ومعاملات BOM والتخطيط الظاهرة داخل MRPACS004.fmx.") ,
  POSLGN: base("POSLGN", "تشغيل نقطة البيع", "pos", "transaction", "NSPC11", [text("USRNM", "اسم مستخدم نقطة البيع", "extracted", true), { id: "P_POS_PASS", label: "كلمة مرور نقطة البيع", type: "password", evidence: "extracted", required: true }, select("BRN_NO", "الفرع"), select("P_SERVER_NO", "جهاز نقطة البيع"), select("DRAWER_PORT", "منفذ الدرج"), select("OUT_WH_TYPE", "مستودع الصرف"), { id: "USE_SERIALNO", label: "استخدام الأرقام التسلسلية", type: "select", evidence: "extracted" }, { id: "PRINT_BILL", label: "طباعة الفاتورة", type: "select", evidence: "extracted" }], ["ALL_USERS", "S_BRN", "S_CMPNY", "S_PRD_DTL", "S_BRN_USR_PRIV", "IAS_POS_MACHINE", "IAS_POS_PRIV_MACHINE", "IAS_PARA_POS", "IAS_POS_BILL_MST", "IAS_SYS"], ["CALL_FAV_SCR", "ITEM_POSTING_FLAG", "SERVICE_ITEM", "GENERATE_I_CODE", "DRAWER_PORT", "TRANSFER_SERIAL", "INSRT_VNDR_ITM", "CONN_POS_SYSTEM", "RE_LOGIN"], "عقد دخول نقطة البيع يتضمن المستخدم والجهاز والفرع وإعدادات الطباعة والدرج والأرقام التسلسلية.") ,
  GLST005: base("GLST005", "تفاصيل اليومية", "finance", "inquiry", "NSPC13", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("A_CODE", "الحساب"), select("USR", "المستخدم"), text("DOC_NO", "رقم المستند", "inferred"), text("NOTE", "ملاحظة", "extracted")], ["DETAIL_JOURNAL_V", "ACCOUNT", "ACCOUNT_CURR", "IAS_DESC_DOC", "NOTE", "NOTE_DETAIL", "V_DETAILS"], ["WHEN_TAB_PAGE_CHANGED_PRC", "PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "B4SAVE_PRC", "EXIT_PROC"], "عقد استعلام وتفاصيل اليومية مع تبويبات الفحص والحفظ والطباعة؛ القراءة مربوطة بسجل القيود ONEX.") ,
  GLST006: base("GLST006", "ملاحظات القيود", "finance", "inquiry", "NSPC5", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("A_CODE", "الحساب"), select("USR", "المستخدم"), text("NOTE", "الملاحظة", "extracted"), text("NOTE_DETAIL", "تفاصيل الملاحظة", "extracted")], ["DETAIL_JOURNAL_V", "ACCOUNT", "ACCOUNT_CURR", "IAS_DESC_DOC", "IAS_NOTE_TYPES", "NOTE", "NOTE_DETAIL", "V_DETAILS"], ["WHEN_TAB_PAGE_CHANGED_PRC", "PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "AUDIT_PRC", "B4SAVE_PRC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "عقد ملاحظات القيود؛ يستخدم نفس مسار الاستعلام المحاسبي مع تسجيل التدقيق قبل الحفظ.") ,
  ARST006: base("ARST006", "كشف حساب العميل", "sales", "inquiry", "NSPC10", [select("C_CODE", "العميل"), date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("A_CY", "العملة"), text("DOC_NO", "رقم المستند", "inferred"), number("DEBIT", "مدين"), number("CREDIT", "دائن")], ["CUSTOMER", "CUSTOMER_CURR", "IAS_BILL_MST", "IAS_BILL_DTL", "IAS_POST_MST", "IAS_POST_DTL", "IAS_PARA_AR"], ["WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "CHECK_DUPLICATE", "EXIT_PROC"], "عقد استعلام كشف حساب العميل؛ القراءة تستخدم سجل الفواتير والقيود، والحفظ محصور في معايير الاستعلام.") ,
  APST005: base("APST005", "كشف حساب المورد", "purchasing", "inquiry", "NSPC23", [select("V_CODE", "المورد"), date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("A_CY", "العملة"), text("DOC_NO", "رقم المستند", "inferred"), number("DEBIT", "مدين"), number("CREDIT", "دائن")], ["SUPPLIER", "IAS_AP_CNTRCT_MST", "IAS_AP_CNTRCT_DTL", "GR_DETAIL", "ACCOUNT_CURR", "IAS_PARA_AP"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "UPDATE_PROC", "CHECK_DUPLICATE", "EXIT_PROC"], "عقد استعلام كشف حساب المورد؛ القراءة تستخدم سجل الموردين والعمليات المساندة المتاحة في ONEX.") ,
  INVT004: base("INVT004", "حركة المخزون", "inventory", "inquiry", "NSPC9", [select("I_CODE", "الصنف"), select("W_CODE", "المستودع"), date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("MOVEMENT_TYPE", "نوع الحركة"), number("QTY", "الكمية")], ["IAS_ITM_MST", "IAS_ITM_DTL", "IAS_ITM_WCODE", "IAS_ITEM_SERIAL", "IAS_BATCH_NO", "IAS_OUTGOING_DTL", "IAS_GR_INCOMING_MST"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "QUERY_MASTER_DETAILS", "CHECK_PREVIOUS_MOVEMENT", "KEY_ENTQRY", "KEY_EXEQRY", "PRINT_PROC", "EXIT_PROC"], "عقد استعلام حركة المخزون؛ القراءة مربوطة برصيد الصنف وحركات الفواتير في ONEX.") ,
  POST001: base("POST001", "مبيعات نقطة البيع", "pos", "transaction", "NSPC11", [text("DOC_NO", "رقم الفاتورة", "inferred", true), date("DOC_DATE", "تاريخ الفاتورة"), select("C_CODE", "العميل"), select("W_CODE", "مستودع الصرف"), text("I_CODE", "الصنف", "inferred", true), number("QTY", "الكمية", "inferred", true), number("PRICE", "السعر", "inferred"), number("DISC_AMT", "الخصم", "inferred"), select("PAY_TYPE", "طريقة الدفع")], ["IAS_POS_BILL_MST", "IAS_BILL_MST", "IAS_BILL_DTL", "IAS_POS_MACHINE", "IAS_PARA_POS", "IAS_POST_MST", "IAS_POST_DTL"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "UPDATE_PROC", "CHECK_DUPLICATE", "PRINT_PROC", "RE_LOGIN", "EXIT_PROC"], "عقد مبيعات نقطة البيع؛ الحفظ يستخدم مسار الفاتورة الذرية في ONEX مع مصدر POST001.") ,
  ADMT027: base("ADMT027", "إدارة المستخدمين والصلاحيات", "admin", "transaction", "NSPC2", [text("USR", "اسم المستخدم", "extracted", true), text("USR_NAME", "الاسم", "inferred"), text("EMAIL", "البريد الإلكتروني", "inferred"), select("ROLE", "الدور"), select("BRN_NO", "الفرع"), { id: "ACTIVE", label: "نشط", type: "select", evidence: "inferred" }], ["ALL_USERS", "PRIVILEGE", "S_BRN_USR_PRIV", "USER_R", "USER_OBJECTS", "USER_CONSTRAINTS"], ["WHEN_TAB_PAGE_CHANGED_PRC", "PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "عقد إدارة المستخدمين والصلاحيات مستخرج من تبويبات الإدارة وامتيازات الفروع.") ,
  GLSR001: base("GLSR001", "ملخص القيود المحاسبية", "reports", "report", "NSPC0", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("A_CODE", "الحساب"), select("A_GROUP", "مجموعة الحساب"), select("BRN_NO", "الفرع"), select("REPORT_TYPE", "نوع التقرير")], ["ACCOUNT", "ACCOUNT_GROUPING", "ACCOUNT_REPORT_TYPE", "IAS_ACC_TREE", "IAS_ACCOUNT_CC", "IAS_ACCOUNT_CLASS", "IAS_PARA_GL", "PRIV_ACC"], ["CLEAR_PROC", "LOAD_PARAMETERS", "FILL_ALL_LIST_PRC", "PRE_FORM_PRC", "EXIT_PROC"], "عقد تقرير الحسابات؛ تشغيله مربوط بمسار reports.run ومصدره journal_entries في ONEX.") ,
  ARSR041: base("ARSR041", "سجل فواتير المبيعات", "reports", "report", "NSPC11", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("C_CODE", "العميل"), select("W_CODE", "المستودع"), select("STATUS", "الحالة"), text("EXL_PATH", "مسار التصدير", "extracted")], ["CUSTOMER", "IAS_BILL_MST", "IAS_BILL_DTL", "IAS_BILL_MST_ADD_DISC", "IAS_BILL_DTL_ADD_DISC", "IAS_ITEM_MST", "IAS_ITM_WCODE"], ["AFTER_EXE_QRY", "CLEAR_PROC", "EXC_QRY", "EXP_TO_EXCEL", "EXIT_PROC"], "عقد سجل المبيعات؛ القراءة والتصدير مربوطان بتقرير ARSR041 الموجود في ONEX.") ,
  MRPREP001: base("MRPREP001", "تقييم المخزون والتخطيط", "reports", "report", "NSPC1", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("W_CODE", "المستودع"), select("I_CODE", "الصنف"), select("REPORT_TYPE", "نوع التقرير")], ["stock_balances", "stock_movements", "BOM", "DEMAND", "ACTUAL_QTY"], ["PRE_FORM_PRC", "LOAD_PARAMETERS", "FILL_ALL_LIST_PRC", "PRINT_PROC", "EXIT_PROC"], "عقد تقرير التخطيط؛ القراءة مربوطة بتقييم أرصدة المخزون في ONEX.") ,
  HRSI002: base("HRSI002", "ملف الموظف", "hr", "transaction", "NSPC0", [text("EMP_NO", "رقم الموظف", "extracted", true), text("EMP_NAME", "اسم الموظف", "inferred", true), date("JOIN_DATE", "تاريخ الالتحاق"), select("EMP_GROUP", "مجموعة الموظفين"), text("CONTRACT_NO", "رقم العقد", "inferred"), select("STATUS", "الحالة")], ["S_EMP", "S_EMP_PRV", "S_CONN_CNTCT", "S_EMP_GRNTR", "S_GRNTR", "USER", "USER_R"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "ADD_PROC", "ADD_PROC2", "UPDATE_PROC", "DELETE_PROC", "EXIT_PROC"], "عقد ملف الموظف مبني على جداول الموظفين والضمانات والاتصالات الظاهرة في FMX.") ,
  HRSR002: base("HRSR002", "تقارير الموظفين", "hr", "report", "NSPC0", [date("FROM_DATE", "من تاريخ"), date("TO_DATE", "إلى تاريخ"), select("EMP_GROUP", "مجموعة الموظفين"), select("STATUS", "الحالة"), select("REPORT_TYPE", "نوع التقرير")], ["S_EMP", "S_EMP_PRV", "S_CONN_CNTCT", "S_GRNTR", "USER_R"], ["PRE_FORM_PRC", "WHEN_NEW_FORM_INSTANCE_PRC", "POST_FORMS_COMMIT_PRC", "PRINT_PROC", "EXIT_PROC"], "عقد تقرير الموظفين؛ مصدر البيانات يحتاج جدول موظفين ONEX عند توسيع المخطط، مع إبقاء العقد قابلاً للتشغيل.") ,
};

export function getLegacyContract(id: string): LegacyWindowContract | undefined { return legacyContracts[id.replace(/\.fmx$/i, "").toUpperCase()]; }
