WHENEVER SQLERROR EXIT SQL.SQLCODE
SET PAGESIZE 500
SET LINESIZE 240
SET FEEDBACK ON
SET HEADING ON
PROMPT === CURRENT USER ===
SELECT USER, SYS_CONTEXT('USERENV','DB_NAME') DB_NAME, SYS_CONTEXT('USERENV','CURRENT_SCHEMA') CURRENT_SCHEMA FROM DUAL;
PROMPT === OBJECT COUNTS ===
SELECT OBJECT_TYPE, COUNT(*) AS OBJECT_COUNT FROM USER_OBJECTS GROUP BY OBJECT_TYPE ORDER BY OBJECT_TYPE;
PROMPT === CORE TABLE COUNTS ===
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED FROM USER_TABLES WHERE TABLE_NAME IN ('FORM_DETAIL','IAS_FORM_NAME','USER_R','PRIVILEGE','IAS_FRM_FLD_PRIV','S_USR_TP_PRV','S_BRN_USR_PRIV','IAS_USR_LGN_HSTRY','ITEM_MOVEMENT','MASTER_INV','DETAIL_INV','MASTER_JOURNAL_V','DETAIL_JOURNAL_V') ORDER BY TABLE_NAME;
PROMPT === INVALID OBJECTS ===
SELECT OBJECT_TYPE, OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE STATUS <> 'VALID' ORDER BY OBJECT_TYPE, OBJECT_NAME;
EXIT SUCCESS
