WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING ON
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 32767
SPOOL ONYX_EXTRACT/user_groups.csv
SELECT 'GROUP_NO,GROUP_A_NAME,GROUP_E_NAME,ADMIN_USER' FROM DUAL;
SELECT GROUP_NO||','||REPLACE(REPLACE(NVL(GROUP_A_NAME,' '),CHR(10),' '),',',';')||','||REPLACE(REPLACE(NVL(GROUP_E_NAME,' '),CHR(10),' '),',',';')||','||ADMIN_USER FROM IAS_USER_GROUP;
SPOOL OFF
SPOOL ONYX_EXTRACT/screen_privileges.csv
SELECT 'U_ID,FORM_NO,INCLUDE_FLAG,AD_FLAG,DEL_FLAG,MOD_FLAG,VIEW_FLAG,PRINT_FLAG,VWREP_FLAG,VRFY_FLAG,PST_FLAG,F_ORDER_NO' FROM DUAL;
SELECT U_ID||','||FORM_NO||','||INCLUDE_FLAG||','||AD_FLAG||','||DEL_FLAG||','||MOD_FLAG||','||VIEW_FLAG||','||PRINT_FLAG||','||VWREP_FLAG||','||VRFY_FLAG||','||PST_FLAG||','||F_ORDER_NO FROM PRIVILEGE;
SPOOL OFF
SPOOL ONYX_EXTRACT/field_privileges.csv
SELECT 'U_ID,FORM_NO,TAB_NAME,FLD_NAME,PRIV_FLAG,F_ORDER_NO' FROM DUAL;
SELECT U_ID||','||FORM_NO||','||REPLACE(NVL(TAB_NAME,' '),',',';')||','||REPLACE(NVL(FLD_NAME,' '),',',';')||','||PRIV_FLAG||','||F_ORDER_NO FROM IAS_FRM_FLD_PRIV;
SPOOL OFF
SPOOL ONYX_EXTRACT/object_type_privileges.csv
SELECT 'U_ID,FORM_NO,OBJ_NM,TP_NM,PRV_FLG' FROM DUAL;
SELECT U_ID||','||FORM_NO||','||REPLACE(OBJ_NM,',',';')||','||REPLACE(TP_NM,',',';')||','||PRV_FLG FROM S_USR_TP_PRV;
SPOOL OFF
SPOOL ONYX_EXTRACT/branch_privileges.csv
SELECT 'U_ID,BRN_NO,ADD_FLAG,VIEW_FLAG,FILL_FLAG' FROM DUAL;
SELECT U_ID||','||BRN_NO||','||ADD_FLAG||','||VIEW_FLAG||','||FILL_FLAG FROM S_BRN_USR_PRIV;
SPOOL OFF
SPOOL ONYX_EXTRACT/login_history.csv
SELECT 'U_ID,TRMNL_NM,LGN_TYP,LGN_OUT_DATE,LNG_NO,CMP_NO,BRN_NO,BRN_YEAR,BRN_USR,APPL_NO,HSTRY_NO' FROM DUAL;
SELECT U_ID||','||REPLACE(NVL(TRMNL_NM,' '),',',';')||','||LGN_TYP||','||TO_CHAR(LGN_OUT_DATE,'YYYY-MM-DD HH24:MI:SS')||','||LNG_NO||','||CMP_NO||','||BRN_NO||','||BRN_YEAR||','||BRN_USR||','||APPL_NO||','||HSTRY_NO FROM IAS_USR_LGN_HSTRY;
SPOOL OFF
-- USER_R is intentionally not exported here because it contains credential fields.
EXIT SUCCESS
