WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING ON
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 32767
SPOOL ONYX_EXTRACT/form_detail.csv
SELECT 'F_SYS,SYS_NO,FORM_NO,F_PARENT_NO,F_FILE_NAME,F_BT_PRIV,F_INACTIVE,F_ORDER_NO,SCR_ORGNL,SCR_THEME_NO,SCR_TYP,DOC_TYP' FROM DUAL;
SELECT F_SYS||','||SYS_NO||','||FORM_NO||','||F_PARENT_NO||','||REPLACE(NVL(F_FILE_NAME,' '),',',';')||','||F_BT_PRIV||','||F_INACTIVE||','||F_ORDER_NO||','||NVL(SCR_ORGNL,'')||','||NVL(SCR_THEME_NO,'')||','||SCR_TYP||','||NVL(DOC_TYP,'') FROM FORM_DETAIL ORDER BY SYS_NO,F_PARENT_NO,F_ORDER_NO,FORM_NO;
SPOOL OFF
SPOOL ONYX_EXTRACT/form_names.csv
SELECT 'LANG_NO,FORM_NO,FORM_NAME' FROM DUAL;
SELECT LANG_NO||','||FORM_NO||','||REPLACE(REPLACE(NVL(FORM_NAME,' '),CHR(10),' '),',',';') FROM IAS_FORM_NAME ORDER BY FORM_NO,LANG_NO;
SPOOL OFF
SPOOL ONYX_EXTRACT/system_tree.csv
SELECT 'SYS_NO,FORM_NO,PARENT_NO,F_FILE_NAME,FORM_NAME_LANG2,FORM_NAME_LANG3,INACTIVE,ORDER_NO,SCR_TYP,DOC_TYP' FROM DUAL;
SELECT d.SYS_NO||','||d.FORM_NO||','||d.F_PARENT_NO||','||REPLACE(NVL(d.F_FILE_NAME,' '),',',';')||','||REPLACE(REPLACE(NVL(n2.FORM_NAME,' '),CHR(10),' '),',',';')||','||REPLACE(REPLACE(NVL(n3.FORM_NAME,' '),CHR(10),' '),',',';')||','||d.F_INACTIVE||','||d.F_ORDER_NO||','||d.SCR_TYP||','||NVL(d.DOC_TYP,'') FROM FORM_DETAIL d LEFT JOIN IAS_FORM_NAME n2 ON n2.FORM_NO=d.FORM_NO AND n2.LANG_NO=2 LEFT JOIN IAS_FORM_NAME n3 ON n3.FORM_NO=d.FORM_NO AND n3.LANG_NO=3 ORDER BY d.SYS_NO,d.F_PARENT_NO,d.F_ORDER_NO,d.FORM_NO;
SPOOL OFF
EXIT SUCCESS
