WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING ON
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 2000000
SPOOL ONYX_EXTRACT/business_table_counts.csv
SELECT 'TABLE_NAME,ROW_COUNT' FROM DUAL;
SELECT 'ITEM_MOVEMENT,'||COUNT(*) FROM ITEM_MOVEMENT;
SELECT 'MASTER_INV,'||COUNT(*) FROM MASTER_INV;
SELECT 'DETAIL_INV,'||COUNT(*) FROM DETAIL_INV;
SELECT 'ITEMS_COSTING,'||COUNT(*) FROM ITEMS_COSTING;
SELECT 'COST_MASTER,'||COUNT(*) FROM COST_MASTER;
SELECT 'COST_DETAIL,'||COUNT(*) FROM COST_DETAIL;
SELECT 'WAREHOUSE_DETAILS,'||COUNT(*) FROM WAREHOUSE_DETAILS;
SELECT 'IAS_BILL_MST,'||COUNT(*) FROM IAS_BILL_MST;
SELECT 'IAS_BILL_DTL,'||COUNT(*) FROM IAS_BILL_DTL;
SELECT 'IAS_PI_BILL_MST,'||COUNT(*) FROM IAS_PI_BILL_MST;
SELECT 'IAS_PI_BILL_DTL,'||COUNT(*) FROM IAS_PI_BILL_DTL;
SELECT 'MASTER_JOURNAL_V,'||COUNT(*) FROM MASTER_JOURNAL_V;
SELECT 'DETAIL_JOURNAL_V,'||COUNT(*) FROM DETAIL_JOURNAL_V;
SELECT 'IAS_AUDIT_DOC,'||COUNT(*) FROM IAS_AUDIT_DOC;
SPOOL OFF
SPOOL ONYX_EXTRACT/inventory_items.csv
SELECT 'I_CODE,I_NAME,INACTIVE,ITEM_TYPE' FROM DUAL;
SELECT I_CODE||','||REPLACE(REPLACE(NVL(I_A_NAME,' '),CHR(10),' '),',',';')||','||INACTIVE||','||I_TYPE FROM IAS_ITM_MST;
SPOOL OFF
SPOOL ONYX_EXTRACT/warehouses.csv
SELECT 'W_CODE,W_NAME,BRN_NO,INACTIVE' FROM DUAL;
SELECT W_CODE||','||REPLACE(REPLACE(NVL(W_A_NAME,' '),CHR(10),' '),',',';')||','||BRN_NO||','||INACTIVE FROM WAREHOUSE_DETAILS;
SPOOL OFF
-- Full business rows should be exported only after privacy and volume review.
EXIT SUCCESS
