WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING OFF
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 2000000
SET LONGCHUNKSIZE 2000000
SPOOL ONYX_EXTRACT/package_specs.sql
SELECT '/* PACKAGE SPECIFICATIONS: '||OBJECT_NAME||' */' FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE' ORDER BY OBJECT_NAME;
SELECT DBMS_METADATA.GET_DDL('PACKAGE',OBJECT_NAME) FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE' ORDER BY OBJECT_NAME;
SPOOL OFF
SPOOL ONYX_EXTRACT/package_bodies.sql
SELECT '/* PACKAGE BODIES: '||OBJECT_NAME||' */' FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE BODY' ORDER BY OBJECT_NAME;
SELECT DBMS_METADATA.GET_DDL('PACKAGE_BODY',OBJECT_NAME) FROM USER_OBJECTS WHERE OBJECT_TYPE='PACKAGE BODY' ORDER BY OBJECT_NAME;
SPOOL OFF
SPOOL ONYX_EXTRACT/package_arguments.csv
SELECT 'PACKAGE_NAME,OBJECT_NAME,ARGUMENT_NAME,POSITION,IN_OUT,DATA_TYPE' FROM DUAL;
SELECT PACKAGE_NAME||','||OBJECT_NAME||','||NVL(ARGUMENT_NAME,'')||','||POSITION||','||IN_OUT||','||DATA_TYPE FROM USER_ARGUMENTS ORDER BY PACKAGE_NAME,OBJECT_NAME,SEQUENCE;
SPOOL OFF
EXIT SUCCESS
