-- ONEX accounting core — Oracle 19c-compatible reference DDL.
-- Execute only in an isolated test schema after review. No production credentials.

CREATE TABLE ONEX_COMPANY (
  COMPANY_ID NUMBER(19) PRIMARY KEY,
  CODE VARCHAR2(30) NOT NULL UNIQUE,
  NAME VARCHAR2(200) NOT NULL,
  BASE_CURRENCY CHAR(3) NOT NULL,
  ACTIVE_FLAG NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVE_FLAG IN (0,1))
);
CREATE SEQUENCE ONEX_COMPANY_SEQ START WITH 1;

CREATE TABLE ONEX_BRANCH (
  BRANCH_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  CODE VARCHAR2(30) NOT NULL,
  NAME VARCHAR2(200) NOT NULL,
  ACTIVE_FLAG NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVE_FLAG IN (0,1)),
  CONSTRAINT ONEX_BRANCH_UQ UNIQUE (COMPANY_ID,CODE)
);
CREATE SEQUENCE ONEX_BRANCH_SEQ START WITH 1;

CREATE TABLE ONEX_FISCAL_PERIOD (
  PERIOD_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  PERIOD_CODE VARCHAR2(20) NOT NULL,
  FROM_DATE DATE NOT NULL,
  TO_DATE DATE NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL CHECK (STATUS IN ('OPEN','SOFT_CLOSED','CLOSED')),
  CONSTRAINT ONEX_PERIOD_UQ UNIQUE (COMPANY_ID,PERIOD_CODE),
  CONSTRAINT ONEX_PERIOD_DATES_CK CHECK (FROM_DATE <= TO_DATE)
);
CREATE SEQUENCE ONEX_PERIOD_SEQ START WITH 1;

CREATE TABLE ONEX_GL_ACCOUNT (
  ACCOUNT_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  ACCOUNT_CODE VARCHAR2(80) NOT NULL,
  ACCOUNT_NAME VARCHAR2(200) NOT NULL,
  ACCOUNT_TYPE VARCHAR2(30) NOT NULL CHECK (ACCOUNT_TYPE IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE','CONTROL')),
  ACTIVE_FLAG NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVE_FLAG IN (0,1)),
  CONSTRAINT ONEX_ACCOUNT_UQ UNIQUE (COMPANY_ID,ACCOUNT_CODE)
);
CREATE SEQUENCE ONEX_GL_ACCOUNT_SEQ START WITH 1;

CREATE TABLE ONEX_CUSTOMER (
  CUSTOMER_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  CODE VARCHAR2(50) NOT NULL,
  LEGAL_NAME VARCHAR2(250) NOT NULL,
  TAX_ID VARCHAR2(80),
  CURRENCY_CODE CHAR(3) NOT NULL,
  PAYMENT_TERM_DAYS NUMBER(9) DEFAULT 0 NOT NULL CHECK (PAYMENT_TERM_DAYS >= 0),
  CREDIT_LIMIT NUMBER(20,6) DEFAULT 0 NOT NULL CHECK (CREDIT_LIMIT >= 0),
  AR_ACCOUNT_CODE VARCHAR2(80) NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (STATUS IN ('ACTIVE','BLOCKED','CLOSED')),
  CONSTRAINT ONEX_CUSTOMER_UQ UNIQUE (COMPANY_ID,CODE),
  CONSTRAINT ONEX_CUSTOMER_ACCT_FK FOREIGN KEY (COMPANY_ID,AR_ACCOUNT_CODE) REFERENCES ONEX_GL_ACCOUNT(COMPANY_ID,ACCOUNT_CODE)
);
CREATE SEQUENCE ONEX_CUSTOMER_SEQ START WITH 1;

CREATE TABLE ONEX_ITEM (
  ITEM_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  ITEM_CODE VARCHAR2(80) NOT NULL,
  DESCRIPTION VARCHAR2(500) NOT NULL,
  STOCK_FLAG NUMBER(1) DEFAULT 1 NOT NULL CHECK (STOCK_FLAG IN (0,1)),
  REVENUE_ACCOUNT_CODE VARCHAR2(80) NOT NULL,
  INVENTORY_ACCOUNT_CODE VARCHAR2(80),
  ACTIVE_FLAG NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVE_FLAG IN (0,1)),
  CONSTRAINT ONEX_ITEM_UQ UNIQUE (COMPANY_ID,ITEM_CODE),
  CONSTRAINT ONEX_ITEM_REV_FK FOREIGN KEY (COMPANY_ID,REVENUE_ACCOUNT_CODE) REFERENCES ONEX_GL_ACCOUNT(COMPANY_ID,ACCOUNT_CODE)
);
CREATE SEQUENCE ONEX_ITEM_SEQ START WITH 1;

CREATE TABLE ONEX_AR_DOC (
  DOC_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  BRANCH_ID NUMBER(19) NOT NULL REFERENCES ONEX_BRANCH(BRANCH_ID),
  PERIOD_ID NUMBER(19) NOT NULL REFERENCES ONEX_FISCAL_PERIOD(PERIOD_ID),
  CUSTOMER_ID NUMBER(19) NOT NULL REFERENCES ONEX_CUSTOMER(CUSTOMER_ID),
  DOC_TYPE VARCHAR2(30) NOT NULL CHECK (DOC_TYPE IN ('INVOICE','DEBIT_NOTE','CREDIT_NOTE','RECEIPT','REFUND','ADJUSTMENT')),
  DOC_NO VARCHAR2(80) NOT NULL,
  DOC_DATE DATE NOT NULL,
  CURRENCY_CODE CHAR(3) NOT NULL,
  EXCHANGE_RATE NUMBER(20,10) DEFAULT 1 NOT NULL CHECK (EXCHANGE_RATE > 0),
  STATUS VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL CHECK (STATUS IN ('DRAFT','PENDING_APPROVAL','APPROVED','POSTED','VOIDED','REVERSED')),
  SUBTOTAL NUMBER(20,6) DEFAULT 0 NOT NULL,
  TAX_TOTAL NUMBER(20,6) DEFAULT 0 NOT NULL,
  DISCOUNT_TOTAL NUMBER(20,6) DEFAULT 0 NOT NULL,
  GRAND_TOTAL NUMBER(20,6) DEFAULT 0 NOT NULL,
  BASE_GRAND_TOTAL NUMBER(20,6) DEFAULT 0 NOT NULL,
  SOURCE_FORM VARCHAR2(80),
  SOURCE_ID VARCHAR2(120),
  IDEMPOTENCY_KEY VARCHAR2(160),
  CREATED_BY VARCHAR2(100) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  POSTED_BY VARCHAR2(100),
  POSTED_AT TIMESTAMP,
  CONSTRAINT ONEX_DOC_UQ UNIQUE (COMPANY_ID,BRANCH_ID,DOC_TYPE,PERIOD_ID,DOC_NO),
  CONSTRAINT ONEX_DOC_IDEMP_UQ UNIQUE (IDEMPOTENCY_KEY),
  CONSTRAINT ONEX_DOC_TOTAL_CK CHECK (GRAND_TOTAL = SUBTOTAL + TAX_TOTAL - DISCOUNT_TOTAL),
  CONSTRAINT ONEX_DOC_POST_CK CHECK ((STATUS='POSTED' AND POSTED_BY IS NOT NULL AND POSTED_AT IS NOT NULL) OR STATUS<>'POSTED')
);
CREATE SEQUENCE ONEX_AR_DOC_SEQ START WITH 1;

CREATE TABLE ONEX_AR_DOC_LINE (
  DOC_LINE_ID NUMBER(19) PRIMARY KEY,
  DOC_ID NUMBER(19) NOT NULL REFERENCES ONEX_AR_DOC(DOC_ID),
  LINE_NO NUMBER(9) NOT NULL,
  ITEM_ID NUMBER(19) REFERENCES ONEX_ITEM(ITEM_ID),
  ITEM_CODE VARCHAR2(80),
  DESCRIPTION VARCHAR2(500) NOT NULL,
  QUANTITY NUMBER(20,6) DEFAULT 1 NOT NULL CHECK (QUANTITY >= 0),
  UNIT_PRICE NUMBER(20,6) DEFAULT 0 NOT NULL,
  DISCOUNT_AMOUNT NUMBER(20,6) DEFAULT 0 NOT NULL,
  TAX_AMOUNT NUMBER(20,6) DEFAULT 0 NOT NULL,
  LINE_TOTAL NUMBER(20,6) DEFAULT 0 NOT NULL,
  REVENUE_ACCOUNT_CODE VARCHAR2(80) NOT NULL,
  COST_CENTER VARCHAR2(80),
  PROJECT_CODE VARCHAR2(80),
  CONSTRAINT ONEX_DOC_LINE_UQ UNIQUE (DOC_ID,LINE_NO)
);
CREATE SEQUENCE ONEX_AR_DOC_LINE_SEQ START WITH 1;

CREATE TABLE ONEX_AR_DUE (
  DUE_ID NUMBER(19) PRIMARY KEY,
  DOC_ID NUMBER(19) NOT NULL REFERENCES ONEX_AR_DOC(DOC_ID),
  INSTALLMENT_NO NUMBER(9) NOT NULL,
  DUE_DATE DATE NOT NULL,
  AMOUNT NUMBER(20,6) NOT NULL CHECK (AMOUNT > 0),
  SETTLED_AMOUNT NUMBER(20,6) DEFAULT 0 NOT NULL CHECK (SETTLED_AMOUNT >= 0),
  STATUS VARCHAR2(20) DEFAULT 'OPEN' NOT NULL CHECK (STATUS IN ('OPEN','PARTIAL','SETTLED','DISPUTED')),
  CONSTRAINT ONEX_DUE_UQ UNIQUE (DOC_ID,INSTALLMENT_NO),
  CONSTRAINT ONEX_DUE_SETTLED_CK CHECK (SETTLED_AMOUNT <= AMOUNT)
);
CREATE SEQUENCE ONEX_AR_DUE_SEQ START WITH 1;

CREATE TABLE ONEX_GL_JOURNAL (
  JOURNAL_ID NUMBER(19) PRIMARY KEY,
  COMPANY_ID NUMBER(19) NOT NULL REFERENCES ONEX_COMPANY(COMPANY_ID),
  BRANCH_ID NUMBER(19) NOT NULL REFERENCES ONEX_BRANCH(BRANCH_ID),
  PERIOD_ID NUMBER(19) NOT NULL REFERENCES ONEX_FISCAL_PERIOD(PERIOD_ID),
  SOURCE_DOC_ID NUMBER(19) REFERENCES ONEX_AR_DOC(DOC_ID),
  JOURNAL_NO VARCHAR2(80) NOT NULL,
  JOURNAL_DATE DATE NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'POSTED' NOT NULL CHECK (STATUS IN ('POSTED','REVERSED')),
  CONSTRAINT ONEX_JOURNAL_UQ UNIQUE (COMPANY_ID,BRANCH_ID,PERIOD_ID,JOURNAL_NO),
  CONSTRAINT ONEX_JOURNAL_SOURCE_UQ UNIQUE (SOURCE_DOC_ID)
);
CREATE SEQUENCE ONEX_GL_JOURNAL_SEQ START WITH 1;

CREATE TABLE ONEX_GL_LINE (
  JOURNAL_LINE_ID NUMBER(19) PRIMARY KEY,
  JOURNAL_ID NUMBER(19) NOT NULL REFERENCES ONEX_GL_JOURNAL(JOURNAL_ID),
  LINE_NO NUMBER(9) NOT NULL,
  ACCOUNT_CODE VARCHAR2(80) NOT NULL,
  DEBIT NUMBER(20,6) DEFAULT 0 NOT NULL,
  CREDIT NUMBER(20,6) DEFAULT 0 NOT NULL,
  CURRENCY_CODE CHAR(3) NOT NULL,
  AMOUNT_CURRENCY NUMBER(20,6) DEFAULT 0 NOT NULL,
  COST_CENTER VARCHAR2(80),
  PROJECT_CODE VARCHAR2(80),
  CONSTRAINT ONEX_GL_LINE_UQ UNIQUE (JOURNAL_ID,LINE_NO),
  CONSTRAINT ONEX_GL_LINE_SIDE_CK CHECK ((DEBIT=0 AND CREDIT>0) OR (CREDIT=0 AND DEBIT>0))
);
CREATE SEQUENCE ONEX_GL_LINE_SEQ START WITH 1;

CREATE TABLE ONEX_AUDIT_EVENT (
  AUDIT_ID NUMBER(19) PRIMARY KEY,
  OCCURRED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  ACTOR VARCHAR2(100) NOT NULL,
  ACTION_CODE VARCHAR2(80) NOT NULL,
  ENTITY_TYPE VARCHAR2(80) NOT NULL,
  ENTITY_ID VARCHAR2(120) NOT NULL,
  REQUEST_ID VARCHAR2(120),
  BEFORE_HASH VARCHAR2(128),
  AFTER_HASH VARCHAR2(128) NOT NULL
);
CREATE SEQUENCE ONEX_AUDIT_SEQ START WITH 1;

CREATE TABLE ONEX_OUTBOX_EVENT (
  EVENT_ID NUMBER(19) PRIMARY KEY,
  AGGREGATE_TYPE VARCHAR2(80) NOT NULL,
  AGGREGATE_ID VARCHAR2(120) NOT NULL,
  EVENT_TYPE VARCHAR2(120) NOT NULL,
  PAYLOAD_JSON CLOB NOT NULL,
  OCCURRED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PUBLISHED_AT TIMESTAMP,
  ATTEMPTS NUMBER(9) DEFAULT 0 NOT NULL,
  LAST_ERROR VARCHAR2(4000)
);
CREATE SEQUENCE ONEX_OUTBOX_SEQ START WITH 1;

CREATE TABLE ONEX_WINDOW_REGISTRY (
  LEGACY_FORM VARCHAR2(120) PRIMARY KEY,
  DOMAIN_CODE VARCHAR2(30) NOT NULL,
  CORE_CAPABILITY VARCHAR2(80) NOT NULL,
  MIGRATION_PHASE NUMBER(3) NOT NULL,
  LEGACY_STATUS VARCHAR2(30) DEFAULT 'COMPILED_ONLY' NOT NULL,
  NEW_STATUS VARCHAR2(30) DEFAULT 'SPEC_ONLY' NOT NULL,
  LAST_VERIFIED_AT TIMESTAMP,
  NOTES VARCHAR2(1000)
);

CREATE INDEX ONEX_DOC_CUST_IX ON ONEX_AR_DOC(CUSTOMER_ID,STATUS,DOC_DATE);
CREATE INDEX ONEX_DUE_OPEN_IX ON ONEX_AR_DUE(DUE_DATE,STATUS);
CREATE INDEX ONEX_GL_SOURCE_IX ON ONEX_GL_JOURNAL(SOURCE_DOC_ID);
CREATE INDEX ONEX_AUDIT_ENTITY_IX ON ONEX_AUDIT_EVENT(ENTITY_TYPE,ENTITY_ID,OCCURRED_AT);
CREATE INDEX ONEX_OUTBOX_PENDING_IX ON ONEX_OUTBOX_EVENT(PUBLISHED_AT,OCCURRED_AT);

CREATE OR REPLACE TRIGGER ONEX_AR_DOC_IMMUTABLE
BEFORE UPDATE OR DELETE ON ONEX_AR_DOC
FOR EACH ROW
BEGIN
  IF :OLD.STATUS IN ('POSTED','REVERSED') THEN
    RAISE_APPLICATION_ERROR(-20901,'Posted/reversed documents are immutable; use reversal workflow');
  END IF;
END;
/
