WHENEVER SQLERROR EXIT SQL.SQLCODE
SET HEADING ON
SET FEEDBACK OFF
SET PAGESIZE 0
SET LINESIZE 32767
SET LONG 2000000
SET LONGCHUNKSIZE 2000000
SPOOL ONYX_EXTRACT/object_inventory.csv
SELECT 'OBJECT_TYPE,OBJECT_NAME,STATUS' FROM DUAL;
SELECT OBJECT_TYPE||','||OBJECT_NAME||','||STATUS FROM USER_OBJECTS ORDER BY OBJECT_TYPE,OBJECT_NAME;
SPOOL OFF
SPOOL ONYX_EXTRACT/column_inventory.csv
SELECT 'TABLE_NAME,COLUMN_ID,COLUMN_NAME,DATA_TYPE,DATA_LENGTH,NULLABLE' FROM DUAL;
SELECT TABLE_NAME||','||COLUMN_ID||','||COLUMN_NAME||','||DATA_TYPE||','||DATA_LENGTH||','||NULLABLE FROM USER_TAB_COLUMNS ORDER BY TABLE_NAME,COLUMN_ID;
SPOOL OFF
SPOOL ONYX_EXTRACT/constraint_inventory.csv
SELECT 'TABLE_NAME,CONSTRAINT_NAME,CONSTRAINT_TYPE,STATUS,SEARCH_CONDITION' FROM DUAL;
SELECT TABLE_NAME||','||CONSTRAINT_NAME||','||CONSTRAINT_TYPE||','||STATUS||','||REPLACE(REPLACE(NVL(SEARCH_CONDITION,' '),CHR(10),' '),',',';') FROM USER_CONSTRAINTS ORDER BY TABLE_NAME,CONSTRAINT_NAME;
SPOOL OFF
SPOOL ONYX_EXTRACT/index_inventory.csv
SELECT 'TABLE_NAME,INDEX_NAME,INDEX_TYPE,STATUS,UNIQUENESS' FROM DUAL;
SELECT TABLE_NAME||','||INDEX_NAME||','||INDEX_TYPE||','||STATUS||','||UNIQUENESS FROM USER_INDEXES ORDER BY TABLE_NAME,INDEX_NAME;
SPOOL OFF
SPOOL ONYX_EXTRACT/dependency_inventory.csv
SELECT 'NAME,TYPE,REFERENCED_NAME,REFERENCED_TYPE' FROM DUAL;
SELECT NAME||','||TYPE||','||REFERENCED_NAME||','||REFERENCED_TYPE FROM USER_DEPENDENCIES ORDER BY NAME,REFERENCED_NAME;
SPOOL OFF
EXIT SUCCESS
